### ISSUE TITLE
[Docs Bug]: 删除 spark load里的无用信息

### ISSUE THREAD

**Issue by femiiii** [StarRocks/docs.zh-cn#1085]
### Link to the Docs

https://docs.starrocks.com/zh-cn/main/loading/SparkLoad#%E5%88%9B%E5%BB%BA%E8%B5%84%E6%BA%90

### Describe the Bug

![image](https://user-images.githubusercontent.com/103574525/177233841-217e5d75-5f21-411d-82dd-9d8593cfbf45.png)

CREATE RESOURCE 里面的参数信息比 spark load里面的要少，所以参考 CREATE RESOURCE也获取不到更详细的参数信息了，这句话可以拿掉。

**Comment by evelynzhaojie** [comment]
reorganized and fixed
