### ISSUE TITLE
[New Content]: ”SQL 参考“下缺少”SHOW BROKER“的相关文档

### ISSUE THREAD

**Issue by amber-create** [StarRocks/docs.zh-cn#1090]
### Describe the Content

在”SQL 参考“下新增一篇”SHOW BROKER“文档，描述 SHOW BROKER 语句的用法。

**Comment by femiiii** [comment]
指的是这篇文档吗？https://docs.starrocks.com/zh-cn/main/sql-reference/sql-statements/Administration/SHOW%20BROKER
