### ISSUE TITLE
[Improvement]:  add more description about COUNT(DISTINCT) in the COUNT function

### ISSUE THREAD

**Issue by femiiii** [StarRocks/docs.zh-cn#1119]
### Describe the Improvement

https://docs.starrocks.com/zh-cn/2.3/sql-reference/sql-functions/aggregate-functions/count
https://docs.starrocks.com/zh-cn/2.3/using_starrocks/Using_bitmap#%E4%BC%A0%E7%BB%9Fcount_distinct%E8%AE%A1%E7%AE%97

把‘基于bitmap 实现精准去重里面的 传统 count-distinct计算’  内容并到count函数文档中
![image](https://user-images.githubusercontent.com/103574525/177329043-aa2d0082-8a81-447c-9623-671eba2bac24.png)

**Comment by evelynzhaojie** [comment]
fix #1554  更新了count文档，pm说更新后的示例已经足够。
