### ISSUE TITLE
 拼写错误

### ISSUE THREAD

**Issue by wangfan0840** [StarRocks/docs.zh-cn#116]
File: [/quick_start/Deploy.md](https://docs.starrocks.com/zh-cn/main/quick_start/Deploy)

拼写错误
![image](https://user-images.githubusercontent.com/21376480/139617404-3ddeb73a-7952-4ab7-97e9-473cfd10c566.png)

**Comment by Dshadowzh** [comment]
非常感谢，你能提个PR帮我们fix么？
