### ISSUE TITLE
ldap doc优化

### ISSUE THREAD

**Issue by wangyouzhuo** [StarRocks/docs.zh-cn#1160]
File: [/administration/Authentication.md](https://docs.starrocks.com/zh-cn/2.3/administration/Authentication)

FROM用户：“官方ldap认证文档不是很详细，配置了ldap后还要在sr中创建用户？”

**Comment by evelynzhaojie** [comment]
![origin_img_v2_00d8df99-609c-4e02-8f9e-dacf3bfbdcdg](https://user-images.githubusercontent.com/98087056/177722981-bdef0faf-8aa3-4783-bc0a-c5356ee62788.jpg)
