### ISSUE TITLE
TO_BITMAP(expr) 的 expr 是个独立的计算表达式，不依赖其他任务列，导入写法该怎么表示呢

### ISSUE THREAD

**Issue by atidat** [StarRocks/docs.zh-cn#1173]
File: [/sql-reference/sql-functions/aggregate-functions/bitmap.md](https://docs.starrocks.com/zh-cn/2.3/sql-reference/sql-functions/aggregate-functions/bitmap)

**Comment by EsoragotoSpirit** [comment]
Greetings, @atidat . This is the StarRocks technical documentation repository. For usage issue regarding StarRocks, please visit https://github.com/StarRocks/starrocks and file your issue there. Thank you.

**Comment by atidat** [comment]
> Greetings, @atidat . This is the StarRocks technical documentation repository. For usage issue regarding StarRocks, please visit https://github.com/StarRocks/starrocks and file your issue there. Thank you.

gotcha
