### ISSUE TITLE
bitmap_andnot和bitmap_or函数逻辑错误

### ISSUE THREAD

**Issue by github24518** [StarRocks/docs.zh-cn#1189]
File: [/sql-reference/sql-functions/bitmap-functions/bitmap_andnot.md](https://docs.starrocks.com/zh-cn/2.3/sql-reference/sql-functions/bitmap-functions/bitmap_andnot)

1、bitmap_or：
空集合与非空集合的并集为空集合

2、bitmap_andnot
非空集合与空集合的差集为空集合

**Comment by kangkaisen** [comment]
I think our current logic is right. you could refer to https://zh.m.wikipedia.org/zh-hans/%E5%B9%B6%E9%9B%86 空集合与非空集合的并集是非空集合，不是空集合。

**Comment by github24518** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
