### ISSUE TITLE
[New Content]: 缺少 strftime 和 alignment_timestamp 两个函数的描述文档

### ISSUE THREAD

**Issue by amber-create** [StarRocks/docs.zh-cn#1207]
### Describe the Content

![image](https://user-images.githubusercontent.com/57167462/178210040-0d4a192e-1c9a-4ffb-8799-d769c76edc8c.png)
BROKER LOAD 和 SPARK LOAD 里有提到 strftime 和 alignment_timestamp 两个受时区设置影响的函数，但是当前文档里没有这两个函数的描述文档。

**Comment by evelynzhaojie** [comment]
根据rd答复：该函数是导入特有的函数，会在内部转
换成FROM_UNIXTIME函数，并不支持
使用该函数查询
