### ISSUE TITLE
关于哪些模型支持物化视图存在文档间差异

### ISSUE THREAD

**Issue by atidat** [StarRocks/docs.zh-cn#1226]
File: [/table_design/Data_model.md](https://docs.starrocks.com/zh-cn/2.2/table_design/Data_model)

以下文档都基于 v2.2
https://docs.starrocks.com/zh-cn/2.2/table_design/Data_model#%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E-2 => "更新模型目前还不支持物化视图"

https://docs.starrocks.com/zh-cn/2.2/using_starrocks/Materialized_view#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9 => "目前聚合模型、更新模型和明细模型支持创建物化视图，主键模型不支持创建物化视图"

**Comment by EsoragotoSpirit** [comment]
Fixed, closing the issue
