### ISSUE TITLE
官网文档bug

### ISSUE THREAD

**Issue by tunbingALi** [StarRocks/docs.zh-cn#124]
https://docs.starrocks.com/zh-cn/main/table_design/Data_model
create table users (
    user_id bigint NOT NULL,
    name string NOT NULL,
    email string NULL,
    address string NULL,
    age tinyint NULL,
    sex tinyint NULL,
    last_active datetime,
    property0 tinyint NOT NULL,
    property1 tinyint NOT NULL,
    property2 tinyint NOT NULL,
    property3 tinyint NOT NULL,
    ....
) PRIMARY KEY (user_id)
DISTRIBUTED BY HASH(order_id) BUCKETS 4
PROPERTIES("replication_num" = "3");

此建表语句有bug，如下
DISTRIBUTED BY HASH(order_id) BUCKETS 4 
order_id应改成user_id，否则建表失败！

**Comment by Dshadowzh** [comment]
是的，你能帮我们提交一个pr修复么

**Comment by Dshadowzh** [comment]
已经修复
