### ISSUE TITLE
denied 

### ISSUE THREAD

**Issue by pockerfacelee** [StarRocks/docs.zh-cn#1295]
ERROR 1064 (HY000): SELECT command denied to user

sr升级后，查询视图时，需要对视图的关联的源表也要授权？

**Comment by EsoragotoSpirit** [comment]
Greetings, @pockerfacelee . This is the StarRocks technical documentation repository. For usage issue regarding StarRocks, please visit https://github.com/StarRocks/starrocks and file your issue there. Thank you.
