### ISSUE TITLE
路径映射编译为什么需要执行两次编译脚本

### ISSUE THREAD

**Issue by atidat** [StarRocks/docs.zh-cn#1298]
File: [/administration/Build_in_docker.md](https://docs.starrocks.com/zh-cn/main/administration/Build_in_docker)

mkdir {local-path}
cd {local-path}

git clone https://github.com/StarRocks/starrocks.git
cd starrocks
git checkout {branch-name}

docker run -it -v /{local-path}/.m2:/root/.m2 -v /{local-path}/starrocks:/root/starrocks --name {container-name} -d starrocks/dev-env:{branch-name}
**docker exec -it {container-name} /root/starrocks/build.sh**

**docker exec -it {container-name} /root/starrocks/build.sh**

**Comment by EsoragotoSpirit** [comment]
Thank you for pointing out this issue, @atidat . Fixing it.
