### ISSUE TITLE
大量逻辑错误

### ISSUE THREAD

**Issue by wangyouzhuo** [StarRocks/docs.zh-cn#1347]
File: [/loading/Loading_intro.md](https://docs.starrocks.com/zh-cn/main/loading/Loading_intro)

“如果数据源是 Hive，除了使用 Spark Load，推荐使用外部表的方式实现导入。”  难道不能broker load？

“对于 MySQL 数据，推荐通过 [MySQL 外部表](https://docs.starrocks.com/zh-cn/main/using_starrocks/External_table)，使用 insert into new_table select * from external_table 语法导入。” 那oracle呢？pg呢？

对于其他数据源，推荐使用 DataX 和 StarRocks 开发的 [starrockswriter](https://docs.starrocks.com/zh-cn/main/loading/DataX-starrocks-writer) 导入。如果 Broker 或 Spark 程序能够读取对应的数据源，也可采用 Broker Load 或 Spark Load 导入 。 这个“其他数据源”范畴太大了。。。

“关使用 Stream Load 导入数据，可参考 [Stream Load demo]。” 这句话有信息量么

**Comment by EsoragotoSpirit** [comment]
Hi @wangyouzhuo , referring to document issues, we expect our contributors can make some constructive suggestions. And I really don't think that rhetorical question can make things better, especially in an open-source project where people works with kindness and respect. Should you have an answer to your question already, please do let us know in a straightforward way. And if you don't, you can simply bring it out and leave it to us.

**Comment by amber-create** [comment]
“如果数据源是 Hive，除了使用 Spark Load，推荐使用外部表的方式实现导入。” 难道不能broker load？
答复：Broker Load 也可以，这里文档做了补充。

“对于 MySQL 数据，推荐通过 [MySQL 外部表](https://docs.starrocks.com/zh-cn/main/using_starrocks/External_table)，使用 insert into new_table select * from external_table 语法导入。” 那oracle呢？pg呢？
答复：Oracle、PG等数据源都归在下面的“其他数据源”中。这句话是特别针对MySQL数据来说的。

对于其他数据源，推荐使用 DataX 和 StarRocks 开发的 [starrockswriter](https://docs.starrocks.com/zh-cn/main/loading/DataX-starrocks-writer) 导入。如果 Broker 或 Spark 程序能够读取对应的数据源，也可采用 Broker Load 或 Spark Load 导入 。 这个“其他数据源”范畴太大了。。。
答复：“其他数据源”很多，这里可以可以列举几个，具体支持的数据源列表，可以通过starrockswriter这里给的链接，跳转到《使用 DataX 导入 StarRocks》这篇文档，这篇文档里开头就列举了“支持的数据源”。

“关使用 Stream Load 导入数据，可参考 [Stream Load demo]。” 这句话有信息量么
答复：这个 demo 链接的确没有提供多少有效信息，这里删掉。
