### ISSUE TITLE
[Doc Bug] Table is wrongly rendered

### ISSUE THREAD

**Issue by EsoragotoSpirit** [StarRocks/docs.zh-cn#1356]
File: [/loading/RoutineLoad.md](https://docs.starrocks.com/zh-cn/main/loading/RoutineLoad)
![image](https://user-images.githubusercontent.com/104624482/180983473-50c13834-846e-4dd1-9516-16fc94a7702e.png)

**Comment by evelynzhaojie** [comment]
重构了文档，已修复
