### ISSUE TITLE
hive外表doc优化

### ISSUE THREAD

**Issue by wangyouzhuo** [StarRocks/docs.zh-cn#1387]
File: [/using_starrocks/External_table.md](https://docs.starrocks.com/zh-cn/main/using_starrocks/External_table)

“缓存更新” 用户读起来会以为是数据cache的更新 直接说“Hive表元数据更新”啥的 是不是好点？

另外 “配置” 这个标题合理么？毫无信息量。直接说 “访问对象存储” 或者其他描述好一点

应该是先 缓存更新 再说访问存储的章节

**Comment by amber-create** [comment]
fixed at https://github.com/StarRocks/docs.zh-cn/pull/5479 & https://github.com/StarRocks/starrocks/pull/23955/files
