### ISSUE TITLE
exec_mem_limit部分文档有问题

### ISSUE THREAD

**Issue by lcl401615068** [StarRocks/docs.zh-cn#140]
File: [/loading/BrokerLoad.md](https://docs.starrocks.com/zh-cn/main/loading/BrokerLoad)
exec_mem_limit 参数不能指定，会报错：
ERROR 1064 (HY000): exec_mem_limit is invalid property
文档修改下吧

**Comment by jaogoy** [comment]
Could you submit a pull request to the StarRocks's docs.

BTW, I have not found the position.
