### ISSUE TITLE
[Improvement]: add another method to check loading status to broker load

### ISSUE THREAD

**Issue by femiiii** [StarRocks/docs.zh-cn#1404]
### Describe the Improvement

broker load 除了使用 show load 还可以使用curl命令来查看, 语法如下

curl --location-trusted -u {user}:{passwd} \
    http://{hostname}:{port}/api/{database}/_load_info?label={labelname}

这部分的语法参数和返回值说明需要放到导入章节的broker load中: https://docs.starrocks.com/zh-cn/main/loading/BrokerLoad

**Comment by amber-create** [comment]
已在 Broker Load 中添加相关内容；Broker Load 当前走读中，走读后完成发布，官网内容将同步更新。

**Comment by amber-create** [comment]
优化后文档已发布 https://docs-stage.starrocks.com/zh-cn/latest/loading/BrokerLoad
