### ISSUE TITLE
[Docs Bug]: add naming conventions for label

### ISSUE THREAD

**Issue by femiiii** [StarRocks/docs.zh-cn#1426]
### Link to the Docs

https://docs.starrocks.com/zh-cn/main/sql-reference/sql-statements/data-manipulation/BROKER%20LOAD

### Describe the Bug

导入作业标签有命名规则，需要补充，可以验证下这个规则是否正确
![image](https://user-images.githubusercontent.com/103574525/182355964-c7bc24ba-4b67-458c-aace-4ab1d453bb99.png)

**Comment by amber-create** [comment]
STREAM LOAD 和 BROKER LOAD 中添加链接，引流到“系统限制”，便于用户查看标签的命名规范。
STREAM LOAD 和 BROKER LOAD 当前走读中，走读后完成发布，官网内容将同步更新。

**Comment by amber-create** [comment]
优化后文档已发布 https://docs-stage.starrocks.com/zh-cn/latest/loading/StreamLoad
