### ISSUE TITLE
错了一个字

### ISSUE THREAD

**Issue by zyplayer** [StarRocks/docs.zh-cn#143]
File: [/table_design/Data_model.md](https://docs.starrocks.com/zh-cn/main/table_design/Data_model)
和更新模型不同，主键模型允许为非主键列创建bitmap等索引，注意需要建表**是**指定

错了一个字

**Comment by jaogoy** [comment]
Could you submit a pull request ?
Very glad to see your contribution.

**Comment by jaogoy** [comment]
#180 has fixed it.
