### ISSUE TITLE
[Docs]group concat 文档内容补充 orderby distinct

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/docs.zh-cn#1442]
File: [/sql-reference/sql-functions/string-functions/group_concat.md](https://docs.starrocks.com/zh-cn/main/sql-reference/sql-functions/string-functions/group_concat)

orderby 
distinct

**Comment by evelynzhaojie** [comment]
当前语法还不支持直接与 distinct 和order by 一起使用。
