### ISSUE TITLE
[Docs]中文文档标题结构设计的疑问

### ISSUE THREAD

**Issue by wangyouzhuo** [StarRocks/docs.zh-cn#1449]
File: [/unloading/Spark_connector.md](https://docs.starrocks.com/zh-cn/main/unloading/Spark_connector)

1.湖分析 和 数据导入导出是平行的一种场景用例，现在藏的太深了，在"使用sr"里面，建议拎出来做一级标题，或者想想别的方案
2.“数据提取”这个描述直观么？我自己感觉，第一反应读不出来这是啥，我得把里面子标题看完才能知道这是讲导出的。为啥不直接叫“数据导出”之类的？
3.”数据导出“ —> “批量导出” 合适一点吧，数据导出这几个字本身没信息量，因为其他模式也算导出
4.“使用sr”下面的子章节，相互之间无关联性，读起来略乱
5“Spark StarRocks Connector” title和左边title不一样，而且，是不是叫做“利用spark读取sr数据”或者类似描述好一点？标题应该一眼能看出是干啥的好一点？单独一个名词，读者会看不出来；flink同理，sentence case适合我们一点？
6."使用sr"这个title，读起来的感觉是这个标题无信息量

**Comment by evelynzhaojie** [comment]
all fixed, thanks for your suggestion. 
some are newly fixed in #3251
