### ISSUE TITLE
[Docs] should remove some empty lines in the code blocks

### ISSUE THREAD

**Issue by jaogoy** [StarRocks/docs.zh-cn#1478]
File: [/loading/StreamLoad.md](https://docs.starrocks.com/zh-cn/main/loading/StreamLoad)

And, should modify some too long code lines. For example, wrap the line with `\`.

**Comment by amber-create** [comment]
走读优化中，新版本不会有多余空行。

**Comment by amber-create** [comment]
新版本已发布 https://docs-stage.starrocks.com/zh-cn/latest/loading/StreamLoad
