### ISSUE TITLE
[Docs]“本页内容”列表显示不全

### ISSUE THREAD

**Issue by banmoy** [StarRocks/docs.zh-cn#1491]
File: [/administration/Configuration.md](https://docs.starrocks.com/zh-cn/main/administration/Configuration)
`本页内容`列表没有显示`BE 静态参数`和`Broker 配置项`
`

**Comment by EsoragotoSpirit** [comment]
> File: [/administration/Configuration.md](https://docs.starrocks.com/zh-cn/main/administration/Configuration) `本页内容`列表没有显示`BE 静态参数`和`Broker 配置项` `

确认了一下是有的，但是因为列表太长需要往下滚动。

**Comment by banmoy** [comment]
不好意思，我的问题
