### ISSUE TITLE
[Docs]"使用 Docker 部署"页面的安装包下载地址无效

### ISSUE THREAD

**Issue by banmoy** [StarRocks/docs.zh-cn#1493]
File: [/administration/deploy_with_docker.md](https://docs.starrocks.com/zh-cn/main/administration/deploy_with_docker)

<img width="831" alt="Screen Shot 2022-08-10 at 20 52 18" src="https://user-images.githubusercontent.com/11382970/183906220-5d6aee3b-bcca-418c-ac55-53c1497e3c55.png">

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/11382970/183906277-528bc264-da49-4ceb-bdd3-0d4dfa6b1f57.png">

**Comment by EsoragotoSpirit** [comment]
测试过，链接没有问题，可能是其他原因
![image](https://user-images.githubusercontent.com/104624482/184566297-de44378b-f54c-4370-8d48-ecbdb5d06cdc.png)
