### ISSUE TITLE
[Docs]"创建表"文档中的实例没有用到PARTITION

### ISSUE THREAD

**Issue by banmoy** [StarRocks/docs.zh-cn#1498]
File: [/quick_start/Create_table.md](https://docs.starrocks.com/zh-cn/main/quick_start/Create_table)
<img width="821" alt="截屏2022-08-11 19 44 19" src="https://user-images.githubusercontent.com/11382970/184126264-0ca2b763-0ee6-4703-a844-a2482cdad63d.png">

这个示例中没有用到`PARTITION`关键字
<img width="807" alt="image" src="https://user-images.githubusercontent.com/11382970/184126281-562cdecd-854f-4d3d-b24e-6deb19259544.png">

**Comment by evelynzhaojie** [comment]
added to toc
