### ISSUE TITLE
[Docs] HLL类型的描述有问题

### ISSUE THREAD

**Issue by banmoy** [StarRocks/docs.zh-cn#1517]
File: [/sql-reference/sql-statements/data-types/HLL.md](https://docs.starrocks.com/zh-cn/main/sql-reference/sql-statements/data-types/HLL)

这里为什么会有`VARCHAR`的描述
<img width="837" alt="截屏2022-08-12 16 58 41" src="https://user-images.githubusercontent.com/11382970/184321479-3dd0bead-ea1f-4e56-b728-23cd4efa405c.png">

**Comment by evelynzhaojie** [comment]
fix in #1935
