### ISSUE TITLE
[Docs]Bitmap索引图片描述不匹配

### ISSUE THREAD

**Issue by banmoy** [StarRocks/docs.zh-cn#1566]
File: [/using_starrocks/Bitmap_index.md](https://docs.starrocks.com/zh-cn/latest/using_starrocks/Bitmap_index)

图里上面的bitmap应该是`Platform bitmap`
<img width="824" alt="image" src="https://user-images.githubusercontent.com/11382970/185605263-11975a6f-b05a-41f5-8b7e-e67c5e3522fa.png">

**Comment by femiiii** [comment]
already modified in this issue: https://github.com/StarRocks/docs.zh-cn/issues/1561
