### ISSUE TITLE
[Docs]HLL相关函数缺少链接

### ISSUE THREAD

**Issue by banmoy** [StarRocks/docs.zh-cn#1576]
File: [/using_starrocks/Using_HLL.md](https://docs.starrocks.com/zh-cn/latest/using_starrocks/Using_HLL)

1. `相关函数`部分只有`HLL_UNION_AGG`有链接，其它函数没有
2. `HLL_UNION_AGG`的链接打开后是`404`

<img width="835" alt="image" src="https://user-images.githubusercontent.com/11382970/185734611-f23e75f0-3426-43e1-ac84-c7458ba58dec.png">

<img width="873" alt="image" src="https://user-images.githubusercontent.com/11382970/185734607-39bcd7fb-1bc1-4d89-9d6c-592c12eabc70.png">

**Comment by evelynzhaojie** [comment]
fixed in #3977
