### ISSUE TITLE
[Docs Bug]: The Chinese version of manual is different from the Eng version.

### ISSUE THREAD

**Issue by dengliu** [StarRocks/docs.zh-cn#1584]
### Link to the Docs

https://docs.starrocks.com/zh-cn/latest/sql-reference/sql-functions/math-functions/round
VS
https://docs.starrocks.com/en-us/latest/sql-reference/sql-functions/math-functions/round

### Describe the Bug

The CN version has all the math operators  but  the EN version doesn't

**Comment by evelynzhaojie** [comment]
历史一些中文函数文档缺英文，会在下个双月补上。

**Comment by evelynzhaojie** [comment]
the missing english function docs have been added to the doc website
