### ISSUE TITLE
怎么使用group_concat distinct里面的数据去重复,或者怎么使用其他的方法满足

### ISSUE THREAD

**Issue by ku666** [StarRocks/docs.zh-cn#160]
1064 - group_concat does not support DISTINCT, Time: 0.007000s

group_by(distinct aaa)

**Comment by Dshadowzh** [comment]
还不支持 但是已经在开发中了

**Comment by ku666** [comment]
好的 开发完了告知下，谢谢大佬

**Comment by jaogoy** [comment]
https://github.com/StarRocks/starrocks/issues/648
