### ISSUE TITLE
[Docs] 需要补充“逻辑视图”相关内容

### ISSUE THREAD

**Issue by amber-create** [StarRocks/docs.zh-cn#1672]
File: [/reference/System_limit.md](https://docs.starrocks.com/zh-cn/latest/reference/System_limit)

**Comment by amber-create** [comment]
![GOZNYh9q02](https://user-images.githubusercontent.com/57167462/188598433-b90e0c6b-77bc-4bc7-a1c5-7f0aff73d49e.jpg)

**Comment by evelynzhaojie** [comment]
fix in #2092
