### ISSUE TITLE
[Docs] StreamLoad导入的JSON示例有问题

### ISSUE THREAD

**Issue by banmoy** [StarRocks/docs.zh-cn#1725]
File: [/loading/StreamLoad.md](https://docs.starrocks.com/zh-cn/latest/loading/StreamLoad)

下图中
1. 数据文件名称需要修改
2. 实例中没有所说的用户 ID、用户姓名和用户得分三列数据
<img width="804" alt="image" src="https://user-images.githubusercontent.com/11382970/189568802-f74d8da9-b3b9-40a6-81a9-db491116ea47.png">

**Comment by amber-create** [comment]
already fixed
