### ISSUE TITLE
[Docs] There should be a `create external catalog` statement in the SQL reference

### ISSUE THREAD

**Issue by jaogoy** [StarRocks/docs.zh-cn#1754]
File: [/using_starrocks/Manage_data.md](https://docs.starrocks.com/zh-cn/latest/using_starrocks/Manage_data)

I can find the `create external catalog` statement in the SQL reference.
And we should move the syntax part into the SQL reference, and use reference links here in the `using` documents.

**Comment by evelynzhaojie** [comment]
added at https://docs.starrocks.io/zh-cn/latest/sql-reference/sql-statements/data-definition/CREATE%20EXTERNAL%20CATALOG#%E8%AF%AD%E6%B3%95
