### ISSUE TITLE
[Docs]broker load 是否支持华为云obs文件导入？

### ISSUE THREAD

**Issue by yingtingdong** [StarRocks/docs.zh-cn#1821]
File: [/loading/BrokerLoad.md](https://docs.starrocks.com/zh-cn/latest/loading/BrokerLoad)
![image](https://user-images.githubusercontent.com/17868027/190838901-debf4d72-0ae7-4008-bc9e-58ea3d30dd7b.png)

**Comment by rickif** [comment]
尚不支持

**Comment by amber-create** [comment]
supported now. See https://docs.starrocks.io/zh-cn/latest/loading/BrokerLoad
