### ISSUE TITLE
[Docs] 格式问题：SQL 格式没有缩进，curl 的没有这行太长了

### ISSUE THREAD

**Issue by jaogoy** [StarRocks/docs.zh-cn#1822]
File: [/sql-reference/sql-functions/bitmap-functions/base64_to_bitmap.md](https://docs.starrocks.com/zh-cn/latest/sql-reference/sql-functions/bitmap-functions/base64_to_bitmap)

**Comment by evelynzhaojie** [comment]
fixed in #3614
