### ISSUE TITLE
海外用户需要 CANCEL REFRESH MATERIALIZED VIEW，可以先写英文再写中文

### ISSUE THREAD

**Issue by evelynzhaojie** [StarRocks/docs.zh-cn#1907]
### Describe the Content

![image](https://user-images.githubusercontent.com/98087056/192187067-c9920858-4b8f-47fe-ba16-2cd7dad8dc4c.png)

View all materialized views under this database
SHOW MATERIALIZED VIEW [IN|FROM db_name]

View the table structure of the specified materialized view
DESC table_name all ( DESC/DESCRIBE mv_name is no longer supported)

View the processing progress of a materialized view
SHOW ALTER MATERIALIZED VIEW FROM db_name

**Comment by evelynzhaojie** [comment]
庞帆提交issue

**Comment by EsoragotoSpirit** [comment]
Fixed
