### ISSUE TITLE
[Docs]create table文档修改

### ISSUE THREAD

**Issue by azp1996** [StarRocks/docs.zh-cn#1908]
File: [/quick_start/Create_table.md](https://docs.starrocks.io/zh-cn/latest/quick_start/Create_table)
![image](https://user-images.githubusercontent.com/57356180/192190392-9631d9e0-0630-453d-9a39-547b3667a893.png)
逗号是英文的，还有句子整体讲出来很奇怪，其他用户可以去掉

**Comment by evelynzhaojie** [comment]
fix in #1935
