### ISSUE TITLE
[Docs] `stddev`和`stddev_pop` 的迷惑“示例”

### ISSUE THREAD

**Issue by asterix314** [StarRocks/docs.zh-cn#1946]
File: [/sql-reference/sql-functions/aggregate-functions/stddev.md](https://docs.starrocks.io/zh-cn/latest/sql-reference/sql-functions/aggregate-functions/stddev)

`stddev`和`stddev_pop`不应该是一样的函数吗？为什么“示例”里面两个函数应用于同一个表会返回不同的结果？令人生疑。

**Comment by evelynzhaojie** [comment]
modified the examples in doc
