### ISSUE TITLE
[Docs] Incomplete parameter descriptions 

### ISSUE THREAD

**Issue by amber-create** [StarRocks/docs.zh-cn#1980]
File: [/administration/Configuration.md](https://docs.starrocks.io/zh-cn/latest/administration/Configuration)

![A1QcETZISP](https://user-images.githubusercontent.com/57167462/194741548-d7828021-5033-47f5-9004-26f23c3e9736.jpg)

sys_log_roll_interval、audit_log_roll_interval、和 dump_log_roll_interval 三个参数，取值范围都是 DAY 或 HOUR，对应地，文件名后缀就是 yyyyMMdd（取值为 DAY 时）或 yyyyMMddHH（取值为 HOUR 时）。

**Comment by evelynzhaojie** [comment]
fixed
