### ISSUE TITLE
[Docs Bug]: 确认 last_query_id 描述是否准确

### ISSUE THREAD

**Issue by femiiii** [StarRocks/docs.zh-cn#2033]
### Link to the Docs

https://docs.starrocks.io/zh-cn/latest/sql-reference/sql-functions/utility-functions/last_query_id

### Describe the Bug

![image](https://user-images.githubusercontent.com/103574525/195342954-509a1886-6781-4dbc-8f3c-21ebffe897c1.png)
这里的 query ID 应该是导出任务的 query ID, 和查询貌似没有关系。需要确认一下

**Comment by evelynzhaojie** [comment]
![image](https://user-images.githubusercontent.com/98087056/195481389-7047ca4f-ef61-4830-9309-8b25c4d536aa.png)
