### ISSUE TITLE
[Docs] Q21 SQL has syntax issue, if copy from doc

### ISSUE THREAD

**Issue by mateng0915** [StarRocks/docs.zh-cn#2080]
File: [/benchmarking/TPC-H_Benchmark.md](https://docs.starrocks.io/zh-cn/latest/benchmarking/TPC-H_Benchmark)

--Q21
select s_name, count(*) as numwait
from  supplier,  lineitem l1,  orders,  nation
where
  s_suppkey = l1.l_suppkey
  and o_orderkey = l1.l_orderkey
  and o_orderstatus = 'F'
  and l1.l_receiptdate > l1.l_commitdate
  and exists (
    select * from  lineitem l2
    where
      l2.l_orderkey = l1.l_orderkey
      and l2.l_suppkey <> l1.l_suppkey
  )
  and not exists (
    select * from  lineitem l3
    where
      l3.l_orderkey = l1.l_orderkey
      and l3.l_suppkey `<>` l1.l_suppkey
      and l3.l_receiptdate > l3.l_commitdate
  )
  and s_nationkey = n_nationkey
  and n_name = 'SAUDI ARABIA'
group by s_name
order by  numwait desc, s_name;

**in the subquery condition where  l3.l_suppkey `<>` l1.l_suppkey should be  l3.l_suppkey  <> l1.l_suppkey**

**Comment by femiiii** [comment]
This issue is closed by the pr: https://github.com/StarRocks/starrocks/pull/15046
