### ISSUE TITLE
[Community-P3] Apache Iceberg and Apache Hudi are missing from the data ecosystem diagram.

### ISSUE THREAD

**Issue by WuMenglong** [StarRocks/docs.zh-cn#2136]
### Link to the Docs

https://docs.starrocks.io/zh-cn/2.4/quick_start/Import_and_query#%E5%AF%BC%E5%85%A5%E6%95%B0%E6%8D%AE

### Describe the Bug

In the "Importing data" chapter, in the external table of the data ecology diagram, it is recommended to add Apache Iceberg and Apache Hudi.

**Comment by EsoragotoSpirit** [comment]
@WuMenglong Thank you, we will fix it in future
