### ISSUE TITLE
[Community-P3]“Follower 会通过类 Paxos 的 BDBJE 协议选主出一个 Leader”语句不通顺

### ISSUE THREAD

**Issue by herocc19** [StarRocks/docs.zh-cn#2144]
File: [/introduction/system_architecture.md](https://docs.starrocks.io/zh-cn/2.4/introduction/system_architecture)

Follower 会通过类 Paxos 的 BDBJE 协议**选主**出一个 Leader。
应该是**选举**。

**Comment by evelynzhaojie** [comment]
fix in #2225
