### ISSUE TITLE
[Community-P3]“如果 Leader 节点失败，Follower 会发起新一轮选主”语句不通顺

### ISSUE THREAD

**Issue by herocc19** [StarRocks/docs.zh-cn#2146]
File: [/introduction/system_architecture.md](https://docs.starrocks.io/zh-cn/2.4/introduction/system_architecture)
如果 Leader 节点失败，Follower 会发起新一轮**选主**。
应该是**选举**。

**Comment by evelynzhaojie** [comment]
fix in #2225
