### ISSUE TITLE
[Community-P3]“如图中的 Fragment 包括了Scan, Project, Aggregate”语句逗号为英文逗号，低错。

### ISSUE THREAD

**Issue by herocc19** [StarRocks/docs.zh-cn#2148]
File: [/introduction/features.md](https://docs.starrocks.io/zh-cn/2.4/introduction/features)
如图中的 Fragment 包括了Scan, Project, Aggregate
英文逗号，需改为中文逗号。

**Comment by evelynzhaojie** [comment]
fix in #2225
