### ISSUE TITLE
[Community-P2] The cluster import speed given in the documentation is much lower than the current actual value

### ISSUE THREAD

**Issue by WuMenglong** [StarRocks/docs.zh-cn#2150]
### Link to the Docs

https://docs.starrocks.io/zh-cn/latest/loading/StreamLoad#%E5%8F%82%E6%95%B0%E9%85%8D%E7%BD%AE

### Describe the Bug

在介绍stream_load_default_timeout_second参数时，文中举例时提到：如果待导入数据文件的大小为 10 GB，并且当前 StarRocks 集群的平均导入速度为 10 MB/s，则超时时间应该设置为大于 1024 秒。
当前StarRocks集群的平均导入速度为应在100MB/s以上，导入性能主要受限于集群磁盘IO及BE个数，这里建议根据测试同学反馈的数字修改文档。

**Comment by amber-create** [comment]
文档已修改并发布
