### ISSUE TITLE
[Docs] BUCKETS 是关键字吗？

### ISSUE THREAD

**Issue by hellolilyliuyi** [StarRocks/docs.zh-cn#2252]
File: [/sql-reference/sql-statements/keywords.md](https://docs.starrocks.io/zh-cn/latest/sql-reference/sql-statements/keywords)

**Comment by EsoragotoSpirit** [comment]
![image](https://user-images.githubusercontent.com/104624482/197917562-194f32a1-511e-4a19-a0ab-7a028826cff9.png)
应该不是。按照文档上写的验证方法，这个词建库建表没有报错
