### ISSUE TITLE
[Docs] DATE_ADD里 Interval 的支持范围

### ISSUE THREAD

**Issue by mengde092** [StarRocks/docs.zh-cn#2258]
File: [/sql-reference/sql-functions/date-time-functions/from_unixtime.md](https://docs.starrocks.io/zh-cn/2.3/sql-reference/sql-functions/date-time-functions/from_unixtime)

SELECT DATE_ADD(FROM_UNIXTIME(0), INTERVAL -2208988800 SECOND); 
以上的sql在mysql里返回的是1900-01-01 08:00:00
但是在starrocks里返回null
针对1970-01-01 00:00:00和2038年以后的时间戳对应的描述 要怎么转换？

**Comment by Pslydhh** [comment]
> File: [/sql-reference/sql-functions/date-time-functions/from_unixtime.md](https://docs.starrocks.io/zh-cn/2.3/sql-reference/sql-functions/date-time-functions/from_unixtime)
> 
> SELECT DATE_ADD(FROM_UNIXTIME(0), INTERVAL -2208988800 SECOND); 以上的sql在mysql里返回的是1900-01-01 08:00:00 但是在starrocks里返回null 针对1970-01-01 00:00:00和2038年以后的时间戳对应的描述 要怎么转换？
Thanks for report this!
It caused by -2208988800 exceeds value of INT(-2147483648~2147483647).
We currently do not provide a wider range of parameter.

**Comment by Pslydhh** [comment]
> File: [/sql-reference/sql-functions/date-time-functions/from_unixtime.md](https://docs.starrocks.io/zh-cn/2.3/sql-reference/sql-functions/date-time-functions/from_unixtime)
> 
> SELECT DATE_ADD(FROM_UNIXTIME(0), INTERVAL -2208988800 SECOND); 以上的sql在mysql里返回的是1900-01-01 08:00:00 但是在starrocks里返回null 针对1970-01-01 00:00:00和2038年以后的时间戳对应的描述 要怎么转换？

Thanks for report this!
It caused by -2208988800 exceeds value of INT(-2147483648~2147483647).
We currently do not provide a wider range of parameter.

**Comment by Pslydhh** [comment]
> File: [/sql-reference/sql-functions/date-time-functions/from_unixtime.md](https://docs.starrocks.io/zh-cn/2.3/sql-reference/sql-functions/date-time-functions/from_unixtime)
> 
> SELECT DATE_ADD(FROM_UNIXTIME(0), INTERVAL -2208988800 SECOND); 以上的sql在mysql里返回的是1900-01-01 08:00:00 但是在starrocks里返回null 针对1970-01-01 00:00:00和2038年以后的时间戳对应的描述 要怎么转换？

You can use 
```
SELECT DATE_ADD(FROM_UNIXTIME(0), INTERVAL -2147483648 ~ 2147483647 second);
```
to get 
```
1901-12-14 04:45:52 ~ 2038-01-19 11:14:07
```
