### ISSUE TITLE
[Community + P1] 按照升级步骤， stop cluster while集群失败（由于pid文件被移除）

### ISSUE THREAD

**Issue by huangfeng1993** [StarRocks/docs.zh-cn#2259]
### Link to the Docs

https://docs.starrocks.io/zh-cn/latest/administration/Cluster_administration#%E5%8D%87%E7%BA%A7-be-%E8%8A%82%E7%82%B9

### Describe the Bug

完全按照上诉步骤，由于pid文件在bin目录，被mv到其他目录， 从而stop不掉集群。建议加个mv bin.bak/be.pid bin的操作。
fe升级类似。

**Comment by EsoragotoSpirit** [comment]
Fix via #2870
