### ISSUE TITLE
[Community-p1] wrong command in "temporary partition"

### ISSUE THREAD

**Issue by evelynzhaojie** [StarRocks/docs.zh-cn#2283]
File: [/table_design/Temporary_partition.md](https://docs.starrocks.io/zh-cn/latest/table_design/Temporary_partition)

![img_v2_108ef53e-1de1-43f0-9fc5-c9ba4bb3c27g](https://user-images.githubusercontent.com/98087056/198461975-9aea17fd-7aa9-4128-8461-c0985013f3fa.jpg)

**Comment by evelynzhaojie** [comment]
submitted by 郑荣

**Comment by evelynzhaojie** [comment]
fix in #2318

**Comment by hellolilyliuyi** [comment]
Fixed in [#2797](https://github.com/StarRocks/docs.zh-cn/pull/2797)
