### ISSUE TITLE
[Community-P3]“动态分区通过 PEROPERTIES 进行配置。”，低错，应该是PROPERTIES

### ISSUE THREAD

**Issue by herocc19** [StarRocks/docs.zh-cn#2339]
File: [/table_design/Data_distribution.md](https://docs.starrocks.io/zh-cn/2.4/table_design/Data_distribution)

**Comment by wanghuan2054** [comment]
I've already submited PR https://github.com/StarRocks/docs.zh-cn/pull/2328
