### ISSUE TITLE
[Docs]”ALTER TABLE 也适用于修改 PEROPERTIES 中的其他配置项。”中PEROPERTIES应该是PROPERTIES

### ISSUE THREAD

**Issue by herocc19** [StarRocks/docs.zh-cn#2340]
File: [/table_design/Data_distribution.md](https://docs.starrocks.io/zh-cn/2.4/table_design/Data_distribution)

**Comment by wanghuan2054** [comment]
I've already submited PR https://github.com/StarRocks/docs.zh-cn/pull/2328
