### ISSUE TITLE
[Community-P3]"StarRocks 1.16 及以后支持该功能。"语句不通顺

### ISSUE THREAD

**Issue by herocc19** [StarRocks/docs.zh-cn#2343]
File: [/table_design/Data_distribution.md](https://docs.starrocks.io/zh-cn/2.4/table_design/Data_distribution)
建议修改为：
StarRocks 1.16 及以后**版本**支持该功能。

**Comment by hellolilyliuyi** [comment]
Fixed in [#2802](https://github.com/StarRocks/docs.zh-cn/pull/2802)
