### ISSUE TITLE
[Community-P3]“ALTER TABLE 也适用于修改 PEROPERTIES 中的其他配置项。”语句中 PEROPERTIES 错误，正确为PROPERTIES

### ISSUE THREAD

**Issue by herocc19** [StarRocks/docs.zh-cn#2345]
File: [/table_design/dynamic_partition.md](https://docs.starrocks.io/zh-cn/2.4/table_design/dynamic_partition)

**Comment by wanghuan2054** [comment]
I've submitted pr #2328
