### ISSUE TITLE
[Community-P2]"如果待导入数据文件的大小为 10 GB，并且当前 StarRocks 集群的平均导入速度为 100 MB/s，则超时时间应该设置为大于 100 秒。"，该语句中的计算有误。

### ISSUE THREAD

**Issue by herocc19** [StarRocks/docs.zh-cn#2362]
File: [/loading/StreamLoad.md](https://docs.starrocks.io/zh-cn/latest/loading/StreamLoad)
如果待导入数据文件的大小为 10 GB，并且当前 StarRocks 集群的平均导入速度为 100 MB/s。
则：
$导入作业的超时时间\gt \frac{10 \times 1024}{100}=102.4$
则超时时间应该设置为大于 103秒 。

**Comment by amber-create** [comment]
Actually your calculation is correct, and that's how I did the calculation while composing the article. Yet the result "100" is concluded by R&D, as they regard this is just an approximate result, and the user may roughly use the formula (10 x 1000)/100 =  100 and that's acceptable.
