### ISSUE TITLE
[Community-p2]从 Google GCS 导入的说明有误

### ISSUE THREAD

**Issue by herocc19** [StarRocks/docs.zh-cn#2364]
File: [/loading/BrokerLoad.md](https://docs.starrocks.io/zh-cn/latest/loading/BrokerLoad)
[从 Google GCS 导入](https://docs.starrocks.io/zh-cn/latest/loading/BrokerLoad#%E4%BB%8E-google-gcs-%E5%AF%BC%E5%85%A5)
从  Google GCS 导入数据使用的是 gs 协议，因此文件路径的前缀必须为 gs://。

**Comment by amber-create** [comment]
Tests have been run by R&D engineer and "s3a://" indeed is used for loading data files from Google CGS. So, the doc content is correct. But thanks for your feedback anyway!
