### ISSUE TITLE
[community-P3]"如果 CSV 数据中列的名称、顺序和数量都能与目标表中列完全对应，则无需配置 COLUMNS 。"语句为说明语句，但是未给出该说明语句的类型是说明还是注意。

### ISSUE THREAD

**Issue by herocc19** [StarRocks/docs.zh-cn#2369]
File: [/loading/RoutineLoad.md](https://docs.starrocks.io/zh-cn/2.4/loading/RoutineLoad)
如果 CSV 数据中列的名称、顺序和数量都能与目标表中列完全对应，则无需配置 COLUMNS 。
建议修改该语句为：
> 说明：如果 CSV 数据中列的名称、顺序和数量都能与目标表中列完全对应，则无需配置 COLUMNS 。

**Comment by hellolilyliuyi** [comment]
Fixed in [#2802](https://github.com/StarRocks/docs.zh-cn/pull/2802)
