### ISSUE TITLE
[Communit-P3]“spark0,spark1,spark2 为 StarRocks 中配置的 Spark 资源的名字。”中逗号为英文逗号，低错。

### ISSUE THREAD

**Issue by herocc19** [StarRocks/docs.zh-cn#2372]
File: [/loading/SparkLoad.md](https://docs.starrocks.io/zh-cn/2.4/loading/SparkLoad)

**Comment by wanghuan2054** [comment]
I've submitted PR https://github.com/StarRocks/docs.zh-cn/pull/2393 about this problem
