### ISSUE TITLE
[Community-P3]“FE 底层通过执行 yarn 命令去获取正在运行的 application 的状态，以及杀死 application”语句中的“杀死”说法不规范，建议修改为“终止”。

### ISSUE THREAD

**Issue by herocc19** [StarRocks/docs.zh-cn#2374]
File: [/loading/SparkLoad.md](https://docs.starrocks.io/zh-cn/2.4/loading/SparkLoad)
FE 底层通过执行 yarn 命令去获取正在运行的 application 的状态，以及**杀死** application

建议修改为：
FE 底层通过执行 yarn 命令去获取正在运行的 application 的状态，以及**终止** application

**Comment by hellolilyliuyi** [comment]
Fixed in [#2802](https://github.com/StarRocks/docs.zh-cn/pull/2802)
