### ISSUE TITLE
丰富bitmap相关函数

### ISSUE THREAD

**Issue by starsun2013** [StarRocks/docs.zh-cn#239]
希望能够增加bitmap分页查询的函数，比如Apache doris中的bitmap_subset_limit

**Comment by Dshadowzh** [comment]
能简单表述下这个函数的使用场景么？

**Comment by starsun2013** [comment]
使用版本：Server version: 5.1.0 StarRocks version 2.0.1
描述：表中有一个bitmap类型字段，目前使用bitmap_to_string函数转成对应id，当bitmap中量级在50w左右的时候可以正常查询，如果在500w左右的话，会报错ERROR 2027 (HY000): Malformed packet,怀疑是不是数据量的问题。
查看日志，报错如下
<img width="823" alt="image" src="https://user-images.githubusercontent.com/11502764/156146191-37f0ebb0-4b42-4244-b060-3482b8e382ae.png">

**Comment by hellolilyliuyi** [comment]
感谢您的反馈🙏，此Github Issues主要交流文档问题，如果您需要交流功能问题，请提交issue至https://github.com/StarRocks/starrocks/issues，会有专业的技术人员跟进处理～
