### ISSUE TITLE
[coumunity-P3]  code block display  redundant characters error

### ISSUE THREAD

**Issue by wanghuan2054** [StarRocks/docs.zh-cn#2431]
File: [/loading/Flink-connector-starrocks.md](https://docs.starrocks.io/zh-cn/latest/loading/Flink-connector-starrocks)

![image](https://user-images.githubusercontent.com/16768136/198943768-5460a271-cd39-45c6-8d4b-e634174d6dbf.png)

**Comment by evelynzhaojie** [comment]
fixed
