### ISSUE TITLE
[Community-P2]“进入 starrocks-kubernetes-operator**/deploy** 目录”语句错误

### ISSUE THREAD

**Issue by herocc19** [StarRocks/docs.zh-cn#2587]
File: [/administration/k8s_operator_cn.md](https://docs.starrocks.io/zh-cn/latest/administration/k8s_operator_cn)
正确内容是：
进入 **starrocks-kubernetes-operator/deploy** 目录。

**Comment by hellolilyliuyi** [comment]
Fixed in [#2802](https://github.com/StarRocks/docs.zh-cn/pull/2802)
