### ISSUE TITLE
[Community-P3]参考[部署CN ](/部署 CN)，低错

### ISSUE THREAD

**Issue by herocc19** [StarRocks/docs.zh-cn#2588]
File: [/administration/k8s_operator_cn.md](https://docs.starrocks.io/zh-cn/latest/administration/k8s_operator_cn)
![](https://github.com/herocc19/pic/blob/main/Snipaste_2022-11-04_23-58-27.png?raw=true)

**Comment by hellolilyliuyi** [comment]
Fixed in [#2611](https://github.com/StarRocks/docs.zh-cn/pull/2611)
