### ISSUE TITLE
[Community-P3] The configuration of amazon-s3 in the document has a problem with the format after copying and pasting

### ISSUE THREAD

**Issue by WuMenglong** [StarRocks/docs.zh-cn#2648]
### Describe the Improvement

https://docs.starrocks.io/zh-cn/latest/data_source/catalog/hive_catalog#amazon-s3
文档中给出的配置信息，在md中看是正常的，但直接粘贴后格式是这样的：
![image](https://user-images.githubusercontent.com/90299197/200262363-294d3b56-3ed1-4e7f-a0df-934268a55842.png)

本页其他三处配置信息也是同样的情况。

**Comment by evelynzhaojie** [comment]
added the copy button for code snippets and the format is normal now. 
![image](https://user-images.githubusercontent.com/98087056/210034654-4f9b0c4a-4b5b-42cf-b3d8-04450acff169.png)
