### ISSUE TITLE
[Docs] ali 用户反馈：hive外表的对象存储内容调整

### ISSUE THREAD

**Issue by evelynzhaojie** [StarRocks/docs.zh-cn#2668]
File: [/data_source/External_table.md](https://docs.starrocks.io/zh-cn/latest/data_source/External_table)
![img_v2_f48279a2-1606-4098-a566-a986c4fa2a9g](https://user-images.githubusercontent.com/98087056/200305061-c17b8d77-1684-43a3-b9d3-6b7d8f4901f4.png)

**Comment by amber-create** [comment]
Just to close this issue, as the doc has been updated a long time ago.
