### ISSUE TITLE
[Community-P3]   Precautions are repeated

### ISSUE THREAD

**Issue by gaoy121** [StarRocks/docs.zh-cn#2741]
File: [/using_starrocks/Colocate_join.md](https://docs.starrocks.io/zh-cn/latest/using_starrocks/Colocate_join)

注意事项内容重复
![image](https://user-images.githubusercontent.com/55279192/200717718-b22c86a7-bf57-40f7-b6f7-c9bc284cb479.png)

**Comment by hellolilyliuyi** [comment]
Fixed in [#2802](https://github.com/StarRocks/docs.zh-cn/pull/2802)
