### ISSUE TITLE
2.0.1 routine load 在pasued 状态卡死

### ISSUE THREAD

**Issue by 311709000529** [StarRocks/docs.zh-cn#281]
1.19.6 关机重启 之后升级到 2.0.1 routine load 在pasued 状态卡死，出现ReasonOfStateChanged: ErrorReason{errCode = 2, msg='failed to create task: disk 1777165949320192348 on backend 10003 exceed limit usage }

**Comment by jaogoy** [comment]
Is this a bug of the StarRocks system, then you should create an issue in the StarRocks/StarRocks project.

**Comment by 311709000529** [comment]
OK！
