### ISSUE TITLE
[Community-P3] 本页Bitmap、String等类型之间的转化关系图背景有水印

### ISSUE THREAD

**Issue by WuMenglong** [StarRocks/docs.zh-cn#2912]
### Describe the Improvement

https://docs.starrocks.io/zh-cn/latest/using_starrocks/Lateral_join#%E4%BD%BF%E7%94%A8-lateral-join

![image](https://user-images.githubusercontent.com/90299197/201349669-9b4dd923-9698-4a52-9f67-d097f7e3214e.png)

**Comment by evelynzhaojie** [comment]
已修复
