### ISSUE TITLE
[Community-P2] 文档几处参数说明有误，但源md中的已经是更正后的正确信息，清理cookie后查看还是未更新

### ISSUE THREAD

**Issue by WuMenglong** [StarRocks/docs.zh-cn#2949]
### Link to the Docs

https://docs.starrocks.io/zh-cn/latest/administration/Configuration#%E5%AD%98%E5%82%A8%E7%9B%B8%E5%85%B3%E5%8A%A8%E6%80%81%E5%8F%82%E6%95%B0

### Describe the Bug

文档中的参数说明是有问题的：
![image](https://user-images.githubusercontent.com/90299197/201453832-2fb5e91f-6677-40cd-81cd-c8d2d797a8fe.png)

在准备提交PR时发现源md中已经是正确的：
![image](https://user-images.githubusercontent.com/90299197/201453871-ce23fa55-d911-43cf-b3db-36aa762bdba1.png)

清cookie和更换浏览器后发现还是不一致，不确定是什么原因导致的没有更新。

**Comment by EsoragotoSpirit** [comment]
@WuMenglong Thank you for bringing out this issue. Update has been published now.
