### ISSUE TITLE
建议优化文档搜索

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/docs.zh-cn#302]
暂时不支持存在下划线的搜索项，建议支持下划线搜索

**Comment by hffariel** [comment]
已修改，重新build文档后可以看到效果

**Comment by Dshadowzh** [comment]
1. 希望能够搜索的时候有更好的排序，比如搜索标题的权重匹配放在最前面，然后才是内容的匹配，如果可以精确匹配，排序能够高于模糊匹配（两个单词分别匹配）
2. 希望搜索页面增加一个路径，比如现在是展示了标题 #认证方式#LDAP认证，能够展示成：administration > Authentication > #认证方式#LDAP认证，方便知道这个文档的位置

**Comment by EsoragotoSpirit** [comment]
done
