### ISSUE TITLE
[Community-Blog] 审计日志插件fe-plugins-auditloader

### ISSUE THREAD

**Issue by WuMenglong** [StarRocks/docs.zh-cn#3059]
### Describe the Content

https://github.com/WuMenglong/fe-plugins-auditloader/blob/main/README.md

近期将之前编写的审计日志插件源码开放到了github，同时整理了使用文档。社区可对代码及文档随意使用^_^

**Comment by EsoragotoSpirit** [comment]
Added via #4291
