### ISSUE TITLE
modify the states of broker/spark load according to code changes

### ISSUE THREAD

**Issue by evelynzhaojie** [StarRocks/docs.zh-cn#3255]
### Describe the Content

https://github.com/StarRocks/starrocks/issues/10654
![image](https://user-images.githubusercontent.com/98087056/203224530-e91b9037-02e0-43ae-9fde-f5a06309ffad.png)

https://starrocks.atlassian.net/browse/SR-12042

**Comment by amber-create** [comment]
https://github.com/StarRocks/docs.zh-cn/pull/3512
https://github.com/StarRocks/starrocks/pull/14878
