### ISSUE TITLE
[Docs] Every derived table must have its own alias

### ISSUE THREAD

**Issue by jaycyx** [StarRocks/docs.zh-cn#3375]
File: [/sql-reference/sql-statements/data-definition/ALTER TABLE.md](https://docs.starrocks.io/zh-cn/latest/sql-reference/sql-statements/data-definition/ALTER TABLE)

为什么在oracle解析是sql,在starrocks里面都会抛出需要别名的问题

**Comment by evelynzhaojie** [comment]
![image](https://github.com/StarRocks/docs.zh-cn/assets/98087056/a36480f5-99f5-4ce3-8f08-acff7066a190)
派生表必须具有别名。行为和 mysql 一致
