### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by leeLeft** [StarRocks/docs.zh-cn#3388]
### Ask the Question

The materialized view created cannot be displayed with show table command. Is this a bug or for other reasons

**Comment by evelynzhaojie** [comment]
the command for displaying materialized views is SHOW MATERIALIZED VIEW;  https://docs.starrocks.io/en-us/latest/sql-reference/sql-statements/data-manipulation/SHOW%20MATERIALIZED%20VIEW.  Does this help?
