### ISSUE TITLE
query plan疑惑

### ISSUE THREAD

**Issue by sunjianboo** [StarRocks/docs.zh-cn#340]
File: [/administration/Query_planning.md](https://docs.starrocks.com/zh-cn/main/administration/Query_planning)
query plan那里请问是怎么看出colocate都是相同的字段呢？我这里看到的colocate是false，是不是意味着没有进行colocate join?

**Comment by jaogoy** [comment]
reference to https://docs.starrocks.com/zh-cn/main/using_starrocks/Colocation_join#%E6%9F%A5%E7%9C%8B-group-%E4%BF%A1%E6%81%AF

**Comment by EsoragotoSpirit** [comment]
Closing the issue for no newer updates
