### ISSUE TITLE
[Docs] check for all the SR dowload link and update en/cn docs

### ISSUE THREAD

**Issue by evelynzhaojie** [StarRocks/docs.zh-cn#3473]
File: [/quick_start/Deploy.md](https://docs.starrocks.io/zh-cn/2.2/quick_start/Deploy)

for chinese doc, change the download link to https://www.mirrorship.cn/zh-CN/download/community.
for english doc, change to https://www.starrocks.io/download/community.

**Comment by EsoragotoSpirit** [comment]
Fixed in #3474
