### ISSUE TITLE
[Docs] DROP FUNCTION 语法不全

### ISSUE THREAD

**Issue by Zhangruichao** [StarRocks/docs.zh-cn#3496]
File: [/sql-reference/sql-functions/JAVA_UDF.md](https://docs.starrocks.io/zh-cn/2.3/sql-reference/sql-functions/JAVA_UDF)

DROP FUNCTION function_name; 
我在使用该命令的时候报语法错误。

看了其他资料才知道需要,例如这样
DROP FUNCTION function_name(string,string); 

所以文档最好把参数也加上，不仅仅要指定函数名。

**Comment by evelynzhaojie** [comment]
fixed in #3637
