### ISSUE TITLE
[Docs] query cache 请添加 t0 表的测试数据

### ISSUE THREAD

**Issue by wuliLSF** [StarRocks/docs.zh-cn#3746]
File: [/using_starrocks/query_cache.md](https://docs.starrocks.io/zh-cn/2.5/using_starrocks/query_cache)
按照官方文档测试，查看 profile 无法显示 Query Cache 的指标项
排查后是因为没有插入数据的原因，请完善文档，添加插入数据步骤

**Comment by wuliLSF** [comment]
https://docs.starrocks.io/zh-cn/2.5/using_starrocks/query_cache#%E8%AF%AD%E6%84%8F%E7%AD%89%E4%BB%B7
调整用词，语意等价与语义等价

**Comment by amber-create** [comment]
fixed at https://github.com/StarRocks/docs.zh-cn/pull/3980 & https://github.com/StarRocks/starrocks/pull/16139
