### ISSUE TITLE
[Docs] 2.3版本文档 部分函数缺失

### ISSUE THREAD

**Issue by Wenjuan66** [StarRocks/docs.zh-cn#3897]
File: [/introduction/StarRocks_intro.md](https://docs.starrocks.io/zh-cn/2.3/introduction/StarRocks_intro)

参考手册-函数参考-Map 函数、参考手册-函数参考-工具函数-host_name缺失，四个点开均为404页面，没有对应的md文件

![image](https://user-images.githubusercontent.com/48712516/209605023-d98673db-01f2-474a-9f3e-c53ef2758d3e.png)

**Comment by evelynzhaojie** [comment]
thx for your feedback. these four functions have been removed from v2.3. they are new functions of v2.5.
