### ISSUE TITLE
stream_load的curl demo格式不对

### ISSUE THREAD

**Issue by abc982627271** [StarRocks/docs.zh-cn#392]
![image](https://user-images.githubusercontent.com/10295131/162162082-2961e3d9-0512-41ca-a872-7ac07116757e.png)
这个最后的 detailDemo_stream_load 和[ Stream Load](https://docs.starrocks.com/zh-cn/main/loading/StreamLoad)中的不一致，应该修改为detailDemo/_stream_load。

**Comment by dq1201** [comment]
Thank you for your check. It has been modified
