### ISSUE TITLE
集群管理命令demo中有些语句缺少末尾的分号

### ISSUE THREAD

**Issue by abc982627271** [StarRocks/docs.zh-cn#396]
https://docs.starrocks.com/zh-cn/main/sql-reference/sql-statements/account-management/ALTER%20USER
<img width="842" alt="image" src="https://user-images.githubusercontent.com/10295131/162206342-d49f47b3-81df-4a3e-8aa3-5978d7d84531.png">

https://docs.starrocks.com/zh-cn/main/sql-reference/sql-statements/account-management/CREATE%20USER
<img width="855" alt="image" src="https://user-images.githubusercontent.com/10295131/162206270-d50f2217-281c-4b00-a656-e7d8d0a2f4b5.png">

https://docs.starrocks.com/zh-cn/main/sql-reference/sql-statements/account-management/SET%20PASSWORD
![image](https://user-images.githubusercontent.com/10295131/162206105-a4ee12be-29ba-4186-b1d9-75d32a0f66a3.png)
https://docs.starrocks.com/zh-cn/main/sql-reference/sql-statements/account-management/DROP%20USER
<img width="526" alt="image" src="https://user-images.githubusercontent.com/10295131/162206178-681d93e8-9dd7-4c50-95d8-ca3ec3136235.png">

**Comment by jaogoy** [comment]
@abc982627271 你可以直接文档右上角“编辑”提交 PR 修改
