### ISSUE TITLE
[Docs] incorrect link in broker load faq

### ISSUE THREAD

**Issue by evelynzhaojie** [StarRocks/docs.zh-cn#3983]
File: [/faq/loading/Broker_load_faq.md](https://docs.starrocks.io/zh-cn/2.5/faq/loading/Broker_load_faq)

![image](https://user-images.githubusercontent.com/98087056/210327891-634ce23a-8e5f-492f-a3ff-bb0413e96b4b.png)

**Comment by amber-create** [comment]
fixed at https://github.com/StarRocks/docs.zh-cn/pull/4012
