### ISSUE TITLE
[Docs] precentile 函数里建议去掉不必要的一些参数

### ISSUE THREAD

**Issue by jaogoy** [StarRocks/docs.zh-cn#4016]
File: [/sql-reference/sql-functions/percentile-functions/percentile_empty.md](https://docs.starrocks.io/zh-cn/latest/sql-reference/sql-functions/percentile-functions/percentile_empty)

```SQL
...
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false"
);
```
这里除了 replication_num，其他参数都没啥用，建议都去掉。特别是，enable_persistent_index 在这里有什么目的么？

**Comment by jaogoy** [comment]
还有 https://docs.starrocks.io/zh-cn/latest/sql-reference/sql-functions/percentile-functions/percentile_approx_raw#%E7%A4%BA%E4%BE%8B 这里也是

**Comment by evelynzhaojie** [comment]
fixed in #4079
