### ISSUE TITLE
stream load不能使用where

### ISSUE THREAD

**Issue by Ziang-Wang** [StarRocks/docs.zh-cn#403]
File: [/loading/StreamLoad.md](https://docs.starrocks.com/zh-cn/main/loading/StreamLoad
csv文件不可以带header，必须是纯数据，那么csv中有的列，但是表中没有的列，就不可以用where进行这个列的筛选

**Comment by jaogoy** [comment]
你这个列的选择，采用 columns 这个 header 参数来设置

**Comment by EsoragotoSpirit** [comment]
No updates since, closing the issue
