### ISSUE TITLE
提交了创建物化视图命令，看不到

### ISSUE THREAD

**Issue by neorof** [StarRocks/docs.zh-cn#4085]
提交了创建物化视图命令，用命令SHOW ALTER MATERIALIZED VIEW\G以及DESC tbl_name ALL都看不到物化视图以及正在创建中的物化视图，版本2.5

**Comment by evelynzhaojie** [comment]
您好，这里是 StarRocks 文档仓库，用于提交和解决文档相关问题。如果您有产品使用上的功能问题，可以在 starrocsk 代码仓库https://github.com/StarRocks/starrocks/issues 新建 issue，或者直接在微信社区群联系技术支持。

**Comment by Dshadowzh** [comment]
2.5的多表物化视图的 进度和执行情况参考  https://docs.starrocks.io/zh-cn/2.4/using_starrocks/Materialized_view#%E6%9F%A5%E7%9C%8B%E5%A4%9A%E8%A1%A8%E7%89%A9%E5%8C%96%E8%A7%86%E5%9B%BE%E7%9A%84%E6%89%A7%E8%A1%8C%E7%8A%B6%E6%80%81

在物化视图的状态在 task和task_runs 的系统表可以查看
