### ISSUE TITLE
[Docs] Just a typo of show tablet example code 

### ISSUE THREAD

**Issue by Mrzyxing** [StarRocks/docs.zh-cn#4092]
File: [/sql-reference/sql-statements/data-manipulation/SHOW TABLET.md](https://docs.starrocks.io/zh-cn/2.3/sql-reference/sql-statements/data-manipulation/SHOW TABLET)

partiton -> partition
origin code as follow(exist util 2.5-rc) :
```
SHOW TABLET
[FROM [db_name.]table_name | tablet_id] [partiton(partition_name_1, partition_name_1)]
[where [version=
1
] [and backendid=
10000
] [and state="NORMAL|ROLLUP|CLONE|DECOMMISSION"]]
[order by order_column]
[limit [offset,]size]
```

**Comment by evelynzhaojie** [comment]
fixed in #4097
thx for your feedback!
