### ISSUE TITLE
[Docs] Web page in mirroship.cn shows 404

### ISSUE THREAD

**Issue by bearmmx** [StarRocks/docs.zh-cn#4231]
url of web page is https://docs.starrocks.io/zh-cn/2.4/table_design/Data_distribution.md#%E7%A1%AE%E5%AE%9A%E5%88%86%E6%A1%B6%E6%95%B0%E9%87%8F

**Comment by evelynzhaojie** [comment]
pls try this link: https://docs.starrocks.io/zh-cn/2.4/table_design/Data_distribution#%E7%A1%AE%E5%AE%9A%E5%88%86%E6%A1%B6%E6%95%B0%E9%87%8F
