### ISSUE TITLE
Where is the `ALTER TABLE REPLACE PARTITION` command

### ISSUE THREAD

**Issue by jaogoy** [StarRocks/docs.zh-cn#435]
File: [/sql-reference/sql-statements/data-definition/ALTER TABLE.md](https://docs.starrocks.com/zh-cn/main/sql-reference/sql-statements/data-definition/ALTER TABLE)

I found the way to replace temp partition, but I have found the SQL command in SQL reference.
https://docs.starrocks.com/zh-cn/main/faq/Others#%E5%8E%9F%E5%AD%90%E6%9B%BF%E6%8D%A2%E3%80%8C%E5%88%86%E5%8C%BA%E3%80%8D

**Comment by femiiii** [comment]
Already add the corresponding content in this PR: https://github.com/StarRocks/docs.zh-cn/pull/965
