### ISSUE TITLE
Create_table 描述疑问

### ISSUE THREAD

**Issue by imhager** [StarRocks/docs.zh-cn#443]
File: [/quick_start/Create_table.md](https://docs.starrocks.com/zh-cn/main/quick_start/Create_table)

DISTRIBUTED 关键字用于给表 [创建分桶](https://docs.starrocks.com/zh-cn/main/sql-reference/sql-statements/data-definition/CREATE%20TABLE#Syntax)，当前 demo 中使用 make_time, mache_verson 两个字段通过 Hash 算法创建 32 个桶。

看了创建脚本是：`DISTRIBUTED BY HASH(make_time, mache_verson) BUCKETS 8`，个人理解桶的个数应该是8个而不是32呢。

**Comment by EsoragotoSpirit** [comment]
Fixed via #626
