### ISSUE TITLE
[Docs] JSON 数据类型的一个疑问

### ISSUE THREAD

**Issue by neorof** [StarRocks/docs.zh-cn#4473]
File: [/sql-reference/sql-statements/data-types/JSON.md](https://docs.starrocks.io/zh-cn/2.4/sql-reference/sql-statements/data-types/JSON)

如果需要将 JSON 文件中一个 JSON 对象的指定值导入并存储为 JSON 类型，则您需要设置 jsonpaths 为$.a（a 代表指定键）。
如果需要将 JSON 文件中的一个 JSON 对象导入并存储为 JSON 类型，则您需要设置 jsonpaths 为 $。

这句话是什么意思，如果我要将一个json文件
{
    "name": "test",
    "sex": 1,
    "address": {
        "country": "china",
        "pro": "guangdong"
    }
}
导入到表
name varchar
sex tinyint
address json
那么我设置：
format: json
columns： name,sex,address
jsonpaths: [\"$.name \", \"$.sex\", \"$.address\"] 或者[\"$.name \", \"$.sex\", \"$\"]  2种方法都试过，导入不了这个address字段

**Comment by neorof** [comment]
最新测试 jsonpaths: ["$.name ", "$.sex", "$.address"]是没问题的，上面我的测试有点问题，不过文档也有点迷惑性

**Comment by evelynzhaojie** [comment]
fixed description
