### ISSUE TITLE
[Improvement]: hive catalog 支持 HA 模式的配置，请补充到文档中

### ISSUE THREAD

**Issue by dq1201** [StarRocks/docs.zh-cn#4592]
### Describe the Improvement

![1feb8688-b0f3-4c08-bf83-cd7d193e452f](https://user-images.githubusercontent.com/90668098/221512860-9855c328-418d-4612-9f2a-4a841d950587.jpeg)

### Additional Info

https://docs.starrocks.io/zh-cn/latest/data_source/catalog/hive_catalog#hive-metastore
https://docs.starrocks.io/zh-cn/latest/sql-reference/sql-statements/data-definition/ALTER%20RESOURCE#%E8%AF%AD%E6%B3%95

**Comment by amber-create** [comment]
fixed at https://github.com/CelerData/celerdata-cloud-docs/pull/177 - Connect your Github account & [[Doc] update uri descriptions in catalog docs by amber-create · Pull Request #4596 · StarRocks/docs.zh-cn](https://github.com/StarRocks/docs.zh-cn/pull/4596)  & [[Doc] Update uri descriptions in catalog docs by amber-create · Pull Request #18593 · StarRocks/starrocks](https://github.com/StarRocks/starrocks/pull/18593)
