### ISSUE TITLE
IDENTIFIED 拼写错误

### ISSUE THREAD

**Issue by qiaqialuguo** [StarRocks/docs.zh-cn#462]
File: [/sql-reference/sql-statements/account-management/ALTER USER.md](https://docs.starrocks.com/zh-cn/main/sql-reference/sql-statements/account-management/ALTER USER)
ALTER USER =>description =>Syntax
auth_option: {
IDENTIFIED BY 'auth_string'
IDENTIFIED WITH auth_plugin
_**DENTIFIED**_  WITH auth_plugin BY 'auth_string'
IDENTIFIED WITH auth_plugin AS 'auth_string'
}
第三个IDENTIFIED 少了i

**Comment by evelynzhaojie** [comment]
已解决
