### ISSUE TITLE
2.1版及以下：FROM拼写错误

### ISSUE THREAD

**Issue by qiaqialuguo** [StarRocks/docs.zh-cn#464]
File: [/sql-reference/sql-statements/data-manipulation/SELECT.md](https://docs.starrocks.com/zh-cn/2.1/sql-reference/sql-statements/data-manipulation/SELECT)
在2.1版及以下都有
SELECT=》description=》连接(Join)
```
SELECT select_list FROMS
table_or_subquery1, table_or_subquery2 [, table_or_subquery3 ...]
```

**Comment by evelynzhaojie** [comment]
resolved
