### ISSUE TITLE
创建资源组和分类器报错

### ISSUE THREAD

**Issue by wuliLSF** [StarRocks/docs.zh-cn#471]
File: [/administration/Resource_Group.md](https://docs.starrocks.com/zh-cn/main/administration/Resource_Group)
使用官方提供的sql创建资源组和分类器：
create resource_group rg1
to
    (user='rg1_user1', role='rg1_role1', query_type in ('select'), source_ip='192.168.2.1/24'),
    (user='rg1_user2', query_type in ('select'), source_ip='192.168.3.1/24'),
    (user='rg1_user3', source_ip='192.168.4.1/24'),
    (user='rg1_user4')with (
    'cpu_core_limit' = '10',
    'mem_limit' = '20%',
    'type' = 'normal');
报错提示如下：
SQL 错误 [1064] [42000]: property 'concurrent_limit' is absent

**Comment by Dshadowzh** [comment]
补充一个 'concurrency_limit' = '100', 这个地方我们会尽快修复
