### ISSUE TITLE
[Docs] 导入的日期格式是YYYYMMDD, 建表的时候可以用date类型吗？还有分区的时候可以用DAY作为增量吗？EVERY (INTERVAL 1 DAY)

### ISSUE THREAD

**Issue by lihuafengzi** [StarRocks/docs.zh-cn#4748]
File: [/sql-reference/sql-statements/data-types/DATE.md](https://docs.starrocks.io/zh-cn/latest/sql-reference/sql-statements/data-types/DATE)

**Comment by evelynzhaojie** [comment]
创建分区时，可以使用 DAY 作为增量。https://docs.starrocks.io/zh-cn/latest/table_design/Data_distribution
