### ISSUE TITLE
[Docs] 单表物化视图不能使用distinct，这个怎么解决？  很多场景下，就是因为去重耗时，这下好了，优化查询性能的单表物化视图居然不支持distinct，鸡肋啊，食之无味

### ISSUE THREAD

**Issue by lihuafengzi** [StarRocks/docs.zh-cn#4753]
File: [/using_starrocks/Materialized_view-single_table.md](https://docs.starrocks.io/zh-cn/latest/using_starrocks/Materialized_view-single_table)

CREATE MATERIALIZED VIEW cloud_app_point_log_cnt AS
SELECT 
day_no,
application_id,
count(device_id) as cnt,
count(distinct device_id) as device_cnt 
from starrocks.kafka_to_starrocks_cloud_app_point_event_log a  
group by day_no,application_id 
order by day_no,cnt desc
;

ERROR 1064 (HY000): Materialized view does not support distinct function count(DISTINCT `starrocks`.`a`.`device_id`)

**Comment by EsoragotoSpirit** [comment]
Hi, @lihuafengzi , StarRocks' SYNC Materialized Views DO support COUNT(DISTINCT). I reckon the reason this SQL fails is that each materialized view supports only ONE aggregate function for EACH column of the base table. You have defined TWO aggregate functions for `device_id `. Please see [Caution](https://docs.starrocks.io/zh-cn/latest/using_starrocks/Materialized_view-single_table#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9) for details.

**Comment by Dshadowzh** [comment]
单表物化视图当前走的同步刷新的逻辑 限制比较多，你这里主要是碰到了一个列不能创建多个表达式的限制，你这个可以先拆成两个mv。后续我们会在通用的异步物化视图中支持增量构建的模式也能解决实时场景的问题。
