### ISSUE TITLE
[Improvement]:  标题应该是“使用 Lateral Join 实现列转行”

### ISSUE THREAD

**Issue by dq1201** [StarRocks/docs.zh-cn#4755]
### Describe the Improvement

标题应该是“使用 Lateral Join 实现列转行”，准确说是一多行转多行，请和rd确认

### Additional Info

https://docs.starrocks.io/zh-cn/latest/using_starrocks/Lateral_join#%E4%BD%BF%E7%94%A8-lateral-join-%E5%AE%9E%E7%8E%B0%E8%A1%8C%E8%BD%AC%E5%88%97

**Comment by evelynzhaojie** [comment]
already fixed https://docs.starrocks.io/zh-cn/2.3/using_starrocks/Lateral_join
