### ISSUE TITLE
[Docs] ERROR 1064 (HY000): Materialized view partition expression `a`.`day_no` could only ref to base table

### ISSUE THREAD

**Issue by lihuafengzi** [StarRocks/docs.zh-cn#4774]
File: [/sql-reference/sql-statements/data-definition/CREATE MATERIALIZED VIEW.md](https://docs.starrocks.io/zh-cn/latest/sql-reference/sql-statements/data-definition/CREATE MATERIALIZED VIEW)

创建物化视图的时候，使用的分区字段本来就是基表的，还是报错

难道select 里面不能有子查询吗？

![image](https://user-images.githubusercontent.com/21120950/226325817-849f7693-7b7b-4977-9d37-fc7e7ce73a91.png)

**Comment by evelynzhaojie** [comment]
@Astralidea pls take a look

**Comment by EsoragotoSpirit** [comment]
Hi @lihuafengzi , maybe you should check the SQL syntax around this part

**Comment by Astralidea** [comment]
Which version are you using? A subquery that is only supported in version 2.5.

**Comment by EsoragotoSpirit** [comment]
By the way, this repo is for the StarRocks documentation issues. If you want a swift reply on issues over StarRocks usage and bugs, we strongly recommend you post your issue on [StarRocks Forum](https://forum.mirrorship.cn/) or join our community WeChat group.
