### ISSUE TITLE
[Docs] enable_tablet_internal_parallel 参数配置不明确

### ISSUE THREAD

**Issue by sniperking1234** [StarRocks/docs.zh-cn#4805]
File: [/table_design/Data_distribution.md](https://docs.starrocks.io/zh-cn/latest/table_design/Data_distribution)

> 您需要确保系统变量 GLOBAL enable_tablet_internal_parallel为 true，已经开启并行扫描 Tablet

`enable_tablet_internal_parallel` 这个参数没有找到在哪里配置，文档中其他页面也没有出现这个参数。

**Comment by blt-NOP** [comment]
直接用SQL语句`SET GLOBAL enable_tablet_internal_parallel = true;`就可以设置了

**Comment by sniperking1234** [comment]
已找到
