### ISSUE TITLE
样式乱了[Docs]

### ISSUE THREAD

**Issue by xhuihui** [StarRocks/docs.zh-cn#4847]
merge_condition | 否 | 用于指定作为更新生效条件的列名。这样只有当导入的数据中该列的值大于当前值的时候，更新才会生效。参见[通过导入实现数据变更](https://docs.starrocks.io/zh-cn/2.4/loading/Load_to_Primary_Key_tables)。指定的列必须为非主键列，且仅主键模型表支持条件更新。 | | format | 否 | 待导入数据的格式，取值范围：CSV 或者 JSON。默认值：CSV。 | | strip_outer_array | 否 | 是否裁剪 JSON 数据最外层的数组结构。取值范围：TRUE 或者 FALSE。默认值：FALSE。真实业务场景中，待导入的 JSON 数据可能在最外层有一对表示数组结构的中括号 []。这种情况下，一般建议您指定该参数取值为 true，这样 StarRocks 会剪裁掉外层的中括号 []，并把中括号 [] 里的每个内层数组都作为一行单独的数据导入。如果您指定该参数取值为 false，则 StarRocks 会把整个 JSON 数据文件解析成一个数组，并作为一行数据导入。例如，待导入的 JSON 数据为 [ {"category" : 1, "author" : 2}, {"category" : 3, "author" : 4} ]，如果指定该参数取值为 true，则 StarRocks 会把 {"category" : 1, "author" : 2} 和 {"category" : 3, "author" : 4} 解析成两行数据，并导入到目标表中对应的数据行

File: [/sql-reference/sql-statements/data-manipulation/CREATE ROUTINE LOAD.md](https://docs.starrocks.io/zh-cn/2.4/sql-reference/sql-statements/data-manipulation/CREATE ROUTINE LOAD)

**Comment by evelynzhaojie** [comment]
got, will fix asap, thx

**Comment by hellolilyliuyi** [comment]
已修复 #4895
