### ISSUE TITLE
[Docs] 文档中没有体现如何查看临时分区 

### ISSUE THREAD

**Issue by xhuihui** [StarRocks/docs.zh-cn#4852]
File: [/sql-reference/sql-statements/data-definition/ALTER TABLE.md](https://docs.starrocks.io/zh-cn/latest/sql-reference/sql-statements/data-definition/ALTER TABLE)

尝试后 SHOW TEMPORARY PARTITIONS 可以查看

**Comment by hellolilyliuyi** [comment]
https://docs.starrocks.io/zh-cn/latest/table_design/Temporary_partition#%E6%9F%A5%E7%9C%8B%E4%B8%B4%E6%97%B6%E5%88%86%E5%8C%BA
这个文档里有写
