### ISSUE TITLE
公共参数 中应该添加 temporary_partitions 说明 [Docs]

### ISSUE THREAD

**Issue by xhuihui** [StarRocks/docs.zh-cn#4853]
File: [/sql-reference/sql-statements/data-manipulation/STREAM LOAD.md](https://docs.starrocks.io/zh-cn/latest/sql-reference/sql-statements/data-manipulation/STREAM LOAD)

当前没有说明临时分区字段，只有在临时分区说明的时候有个简单示例

**Comment by evelynzhaojie** [comment]
已添加https://docs.starrocks.io/zh-cn/latest/sql-reference/sql-statements/data-manipulation/STREAM%20LOAD
