### ISSUE TITLE
[Docs]链接跳转错误

### ISSUE THREAD

**Issue by wuliLSF** [StarRocks/docs.zh-cn#4916]
File: [/release_notes/release-3.0.md](https://docs.starrocks.io/zh-cn/main/release_notes/release-3.0)

![image](https://user-images.githubusercontent.com/45867247/229682181-6fa0f1ea-3139-4082-9285-b1d6c75a2ae3.png)
![image](https://user-images.githubusercontent.com/45867247/229682301-9a369951-8a45-460a-950a-7c079c9dbf55.png)

**Comment by evelynzhaojie** [comment]
this link works now, thx for your feedback
