### ISSUE TITLE
[主键模型不支持同步物化视图]

### ISSUE THREAD

**Issue by neorof** [StarRocks/docs.zh-cn#4931]
File: [/table_design/Data_model.md](https://docs.starrocks.io/zh-cn/3.0/table_design/Data_model)
![1](https://user-images.githubusercontent.com/30856536/229744266-2abb4211-6534-43b5-83f3-14ea63103a8f.png)
![2](https://user-images.githubusercontent.com/30856536/229744356-4642a271-377d-4427-8704-b6a4ef790d71.png)

主键模型，版本2.5.2-c3772fb，依然不支持创建同步物化视图，文档有误

**Comment by hellolilyliuyi** [comment]
文档已更新
