### ISSUE TITLE
create table as select get Unknown error

### ISSUE THREAD

**Issue by MakoXiao** [StarRocks/docs.zh-cn#500]
File: [/sql-reference/sql-statements/data-definition/CREATE TABLE AS SELECT.md](https://docs.starrocks.com/zh-cn/main/sql-reference/sql-statements/data-definition/CREATE TABLE AS SELECT)

when i use CTAS  with select query use subquery, I got "ERROR 1064 (HY000): Unknown error"
such as :
CREATE TABLE tmp_01 AS
select *
from ( select order_id
                   , row_number() over(partition order_id order by modify_tm) as row_num
           from t_order
) a
where row_num = 1;

**Comment by Astralidea** [comment]
It is might that you need to add a ”by“ after the ”partition“. 
Can you reproduce it now? Or you can provide the original table and version and I'll test it for you.
