### ISSUE TITLE
[Docs] 为什么不支持 substring_index函数

### ISSUE THREAD

**Issue by lzz0924** [StarRocks/docs.zh-cn#5009]
File: [/sql-reference/sql-functions/string-functions/substr.md](https://docs.starrocks.io/zh-cn/latest/sql-reference/sql-functions/string-functions/substr)
为什么不支持 substring_index函数，有什么函数可以替代

**Comment by wangsimo0** [comment]
https://github.com/StarRocks/starrocks/issues/12532 社区正在研发中，已经有开发者认领了这个issue
