### ISSUE TITLE
[Improvement]: spark 连接器需提供编译好的spark 连接器的jar

### ISSUE THREAD

**Issue by dq1201** [StarRocks/docs.zh-cn#5242]
### Describe the Improvement

当前需要用户自己下载编译包，然后进行编译，不方便使用，建议直接提供编译好的依赖的下载链接
![image](https://user-images.githubusercontent.com/90668098/236401249-d8d2bb83-7a07-4d4b-a313-7abc086c9f7f.png)

### Additional Info

https://docs.starrocks.io/zh-cn/latest/unloading/Spark_connector

**Comment by evelynzhaojie** [comment]
已补充直接下载的内容。https://github.com/StarRocks/docs.zh-cn/pull/5251/files
