### ISSUE TITLE
导入概述里导入常见问题链接是“导出”

### ISSUE THREAD

**Issue by evelynzhaojie** [StarRocks/docs.zh-cn#5471]
File: [/loading/Loading_intro.md](https://docs.starrocks.io/zh-cn/latest/loading/Loading_intro)
![image](https://github.com/StarRocks/docs.zh-cn/assets/98087056/02fc6283-46f0-4f50-aa9c-05d1185410e2)

**Comment by amber-create** [comment]
fixed at https://github.com/StarRocks/docs.zh-cn/pull/5473
