### ISSUE TITLE
[Docs Bug]: kerberos 认证方式代码里的 negative 删除

### ISSUE THREAD

**Issue by evelynzhaojie** [StarRocks/docs.zh-cn#5679]
### Link to the Docs

https://docs.mirrorship.cn/zh-cn/latest/sql-reference/sql-statements/data-manipulation/BROKER%20LOAD

### Describe the Bug

<img width="592" alt="image" src="https://github.com/StarRocks/docs.zh-cn/assets/98087056/e483e615-1a37-44ee-b846-6d33c31ef9c3">

这个东西不是撤销导入的时候用的吗？为啥设置kereros的时候要用这个关键词
--这里不需要，帮忙提个pr删了它吧

**Comment by amber-create** [comment]
fixed at https://github.com/StarRocks/docs.zh-cn/pull/5680/files & https://github.com/StarRocks/starrocks/pull/24911/files
