### ISSUE TITLE
Need a article to description the modification between two versions

### ISSUE THREAD

**Issue by jaogoy** [StarRocks/docs.zh-cn#569]
Especially when there are some importance informance to let user known.
For example, users should take care of chunk size if they upgrade from StarRocks v2.0 to StarRocks v2.1.

And, users will know all the new feature articles and import bug fix about the documentation.

**Comment by EsoragotoSpirit** [comment]
Can't we simply add this part to release notes? This should be part of the CHANGELOG unless we want to compare a huge lot of things across major versions.
