### ISSUE TITLE
[Docs] [近似去重] hll_union 的链接失效

### ISSUE THREAD

**Issue by yandongxiao** [StarRocks/docs.zh-cn#5772]
File: [/using_starrocks/Materialized_view-single_table.md](https://docs.starrocks.io/zh-cn/2.5/using_starrocks/Materialized_view-single_table)

以上文表 advertiser_view_record 为例，如果想在查询点击广告的 UV 时实现近似去重查询加速，可基于该明细表创建一张同步物化视图，并使用 [hll_union()](https://docs.starrocks.io/zh-cn/2.5/sql-reference/sql-functions/aggregate-functions/hll_union.md) 函数预先聚合数据。

hll_union 的链接失效了，404。hll_union 的链接地址是：`https://docs.starrocks.io/zh-cn/2.5/sql-reference/sql-functions/aggregate-functions/hll_union.md`。

**Comment by EsoragotoSpirit** [comment]
Hi @yandongxiao , I've tried this link, and it looks fine to me. Perhaps you can try it in a different network environment.

**Comment by yandongxiao** [comment]
The link from StarRocks Doc now is `https://docs.starrocks.io/zh-cn/2.5/sql-reference/sql-functions/aggregate-functions/hll_union`，and it is ok.

**Comment by EsoragotoSpirit** [comment]
Thank you @yandongxiao , I see the problem. I shall report it to our web engineering team.
