### ISSUE TITLE
[Docs] need to give more detail about `offset` when given a negitive value or offset out of the range.

### ISSUE THREAD

**Issue by jaogoy** [StarRocks/docs.zh-cn#6040]
File: [/sql-reference/sql-functions/bitmap-functions/sub_bitmap.md](https://docs.starrocks.io/zh-cn/latest/sql-reference/sql-functions/bitmap-functions/sub_bitmap)

**Comment by evelynzhaojie** [comment]
目前文档里有写到这些信息，我进一步整合一下。
![img_v2_171a1fe7-776b-4638-ae5d-2d0858ae2c4g](https://github.com/StarRocks/docs.zh-cn/assets/98087056/1831797d-dd60-4cb5-8a6a-6e954e80068b)
