### ISSUE TITLE
[Docs]SQL 错误 [1064] [42000]: create partitions failed 经常报这样的错，但重新跑一下sql就好，这是什么情况

### ISSUE THREAD

**Issue by 18681142360** [StarRocks/docs.zh-cn#6085]
File: [/introduction/StarRocks_intro.md](https://docs.starrocks.io/zh-cn/latest/introduction/StarRocks_intro)

**Comment by evelynzhaojie** [comment]
您好，关于产品的 bug 问题，可以在 https://forum.mirrorship.cn/ 论坛发贴，提供详细的信息，会有 rd 工程师来解答。
