### ISSUE TITLE
[Docs]Suggestion: Complete the use case prompt

### ISSUE THREAD

**Issue by pzdogjs** [StarRocks/docs.zh-cn#6114]
File: [/loading/Stream_Load_transaction_interface.md](https://docs.starrocks.io/zh-cn/latest/loading/Stream_Load_transaction_interface)

https://github.com/StarRocks/docs.zh-cn/pull/6113

**Comment by jaogoy** [comment]
`columns` is an optional parameter, and by default, it needn't to be specified.
