### ISSUE TITLE
[Docs] 表设计图片问题

### ISSUE THREAD

**Issue by dalu610** [StarRocks/docs.zh-cn#6253]
File: [/table_design/StarRocks_table_design.md](https://docs.starrocks.io/zh-cn/latest/table_design/StarRocks_table_design)
![image](https://github.com/StarRocks/docs.zh-cn/assets/7900299/7d21c2e5-206b-4751-ab24-4f35c66c2a2e)
图有点问题吧？

**Comment by hellolilyliuyi** [comment]
![image](https://github.com/StarRocks/docs.zh-cn/assets/96421222/728b40a2-9b31-43be-bd79-3a2a1633e478)
hihi 这个图更新过了 您看下呢
