### ISSUE TITLE
[Docs]https://docs.starrocks.io/zh-cn/2.2/sql-reference/sql-functions/condition-functions/coalesce，【CASE Function has no docs】

### ISSUE THREAD

**Issue by chenju0606** [StarRocks/docs.zh-cn#6289]
File: [/sql-reference/sql-functions/condition-functions/coalesce.md](https://docs.starrocks.io/zh-cn/2.2/sql-reference/sql-functions/condition-functions/coalesce)

**Comment by evelynzhaojie** [comment]
thanks, we have fixed this error
