### ISSUE TITLE
show full fields from table_statistic_v1  execute fail

### ISSUE THREAD

**Issue by weiwei940928** [StarRocks/docs.zh-cn#635]
File: [/sql-reference/sql-statements/data-manipulation/SHOW DATA.md](https://docs.starrocks.com/zh-cn/main/sql-reference/sql-statements/data-manipulation/SHOW DATA)

**Comment by femiiii** [comment]
any more information about this issue?

**Comment by femiiii** [comment]
Could you provide error message here so we can recognize what error it is

**Comment by femiiii** [comment]
This issue has been closed because there is no valid information for R&D to identify the cause of this error.
