### ISSUE TITLE
Unnecessary spaces in the following arrays: {" a ": 1, " c ": 2} < {" b ": 1, " a ": 2}

### ISSUE THREAD

**Issue by amber-create** [StarRocks/docs.zh-cn#637]
File: [/sql-reference/sql-functions/json-functions/json-operators.md](https://docs.starrocks.com/zh-cn/2.2/sql-reference/sql-functions/json-functions/json-operators)

数组里 a、c、b前后多余空格。
![image](https://user-images.githubusercontent.com/57167462/169734786-0d69c730-47c6-4e83-9491-e8594c91e94e.png)

**Comment by evelynzhaojie** [comment]
已解决
