### ISSUE TITLE
[Docs] 确定分桶数量 链接问题

### ISSUE THREAD

**Issue by yandongxiao** [StarRocks/docs.zh-cn#6383]
File: [/table_design/Sort_key.md](https://docs.starrocks.io/zh-cn/latest/table_design/Sort_key)

请参见 [确定分桶数量](https://docs.starrocks.io/zh-cn/latest/Data_distribution#%E7%A1%AE%E5%AE%9A%E5%88%86%E6%A1%B6%E6%95%B0%E9%87%8F)。
链接失效。

https://docs.starrocks.io/zh-cn/latest/Data_distribution#%E7%A1%AE%E5%AE%9A%E5%88%86%E6%A1%B6%E6%95%B0%E9%87%8F

**Comment by evelynzhaojie** [comment]
fixed at #6386
