### ISSUE TITLE
Operators should be wrapped in code blocks

### ISSUE THREAD

**Issue by amber-create** [StarRocks/docs.zh-cn#639]
File: [/sql-reference/sql-functions/json-functions/json-operators.md](https://docs.starrocks.com/zh-cn/2.2/sql-reference/sql-functions/json-functions/json-operators)
![image](https://user-images.githubusercontent.com/57167462/169762626-7a0ceb53-2b50-4675-839a-5bf84d7d2daa.png)

**Comment by evelynzhaojie** [comment]
已解决
