### ISSUE TITLE
请问一下，我新建了oceanbase的外表，然后将数据通过insert into 到ob的外表中，报错only support insert into olap table or mysql table。ob走的是mysql协议，为啥不支持？[Docs]

### ISSUE THREAD

**Issue by hangsing** [StarRocks/docs.zh-cn#6437]
File: [/unloading/Export.md](https://docs.starrocks.io/zh-cn/latest/unloading/Export)

**Comment by hangsing** [comment]
有没有微信群的，拉我一个呗

**Comment by evelynzhaojie** [comment]
![image](https://github.com/StarRocks/docs.zh-cn/assets/98087056/d7b75a38-8343-4cdf-820b-7db91df3c356)
你好，可以加一下微信社区群，小助手会审核一下然后通过
