### ISSUE TITLE
[Docs] FE 内存的咨询

### ISSUE THREAD

**Issue by Mile-Z** [StarRocks/docs.zh-cn#6488]
File: [/faq/Others.md](https://docs.starrocks.io/zh-cn/3.0/faq/Others)

![image](https://github.com/StarRocks/docs.zh-cn/assets/91326053/08a02cac-5f7d-4470-905a-53f0300e946f)
关于fe元数据的大小，文中提到：一千万个 Tablet 内存使用在 20 GB左右。FE 的内存最多可设置为 20 GB。
正常生产最多应该是大于20gb的吧，请确认下是否有问题呢。而且这个fe是单个的，还是三个fe高可用节点负载均衡后的呢？

**Comment by hellolilyliuyi** [comment]
现在基本按照这个规则来设置fe的 jvm 大小
![img_v2_84175cff-6d51-494f-a8ab-a3b61968eabg](https://github.com/StarRocks/docs.zh-cn/assets/96421222/a265efb2-7272-45fe-9dd2-3c5300936392)
每个fe 都统一的配置, 每个FE都可能成为Leader.

**Comment by evelynzhaojie** [comment]
https://docs.starrocks.io/zh-cn/latest/faq/Others#%E5%A6%82%E4%BD%95%E8%AE%BE%E7%BD%AE-fe-%E7%9A%84%E5%86%85%E5%AD%98%E5%A4%A7%E5%B0%8F
