### ISSUE TITLE
[Docs]超链接失效

### ISSUE THREAD

**Issue by DeH40** [StarRocks/docs.zh-cn#6492]
File: [/table_design/Data_distribution.md](https://docs.starrocks.io/zh-cn/latest/table_design/Data_distribution)
https://docs.starrocks.io/zh-cn/latest/table_design/Data_distribution#%E8%A1%A8%E8%BE%BE%E5%BC%8F%E5%88%86%E5%8C%BA%E6%8E%A8%E8%8D%90 处的[表达式分区](https://docs.starrocks.io/zh-cn/latest/table_design/expression_partitioning.md) 超链接失效

**Comment by evelynzhaojie** [comment]
已修复
