### ISSUE TITLE
[Docs] flink cdc 一些参数没看懂

### ISSUE THREAD

**Issue by huyichao123456** [StarRocks/docs.zh-cn#6521]
File: [/introduction/StarRocks_intro.md](https://docs.starrocks.io/zh-cn/latest/introduction/StarRocks_intro)

flink.starrocks.jdbc-url=jdbc:mysql://<fe_host>:<fe_query_port>
flink.starrocks.load-url= <fe_host>:<fe_http_port>
flink.starrocks.username=user2
flink.starrocks.password=xxxxxx    分别对应的参数是?没看懂

**Comment by evelynzhaojie** [comment]
https://docs.starrocks.io/zh-cn/latest/loading/Flink_cdc_load

**Comment by hellolilyliuyi** [comment]
https://docs.starrocks.io/zh-cn/latest/loading/Flink-connector-starrocks#%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E
这里有相关参数解释哈 我也更新下文档
