### ISSUE TITLE
code block format errors

### ISSUE THREAD

**Issue by amber-create** [StarRocks/docs.zh-cn#664]
File: [/sql-reference/sql-functions/json-functions/json-processing-functions/cast-from-or-to-json.md](https://docs.starrocks.com/zh-cn/2.2/sql-reference/sql-functions/json-functions/json-processing-functions/cast-from-or-to-json)

![image](https://user-images.githubusercontent.com/57167462/170230871-6c25c89d-7742-40ad-94e1-e5be736da2b1.png)

**Comment by evelynzhaojie** [comment]
resolved
