### ISSUE TITLE
Inconsistent feature names: The feature name should be ”资源组管理 (resource group management)"

### ISSUE THREAD

**Issue by amber-create** [StarRocks/docs.zh-cn#670]
File: [/administration/Resource_Group.md](https://docs.starrocks.com/zh-cn/2.2/administration/Resource_Group)

**Comment by amber-create** [comment]
![ZUzNuj9mv8](https://user-images.githubusercontent.com/57167462/170262337-882e755f-09e2-4450-bed7-058f9685e1e3.jpg)

**Comment by EsoragotoSpirit** [comment]
Directly done.
