### ISSUE TITLE
[Docs] 文档里sink.wait-for-continue.timeout-ms的范围有问题

### ISSUE THREAD

**Issue by JoseZW** [StarRocks/docs.zh-cn#7180]
File: [/loading/Flink-connector-starrocks.md](https://docs.starrocks.io/zh-cn/latest/loading/Flink-connector-starrocks)
文档里说明范围是[3000, 600000]。，但是我设置了600000后，报错
<img width="1317" alt="image" src="https://github.com/StarRocks/docs.zh-cn/assets/30175538/a3df6fda-9169-405c-9395-1d4077ba0f19">

**Comment by hellolilyliuyi** [comment]
Thanks. The maximum value of sink.wait-for-continue.timeout-ms is 60000. This bug is fixed in this pr https://github.com/StarRocks/starrocks/pull/35963/files.
