### ISSUE TITLE
[Improvement]: Support subpartition

### ISSUE THREAD

**Issue by colagy** [StarRocks/docs.zh-cn#7182]
### Describe the Improvement

```sql
CREATE TABLE ts (id INT, purchased DATE)
    PARTITION BY RANGE( YEAR(purchased) )
    SUBPARTITION BY HASH( TO_DAYS(purchased) )
    SUBPARTITIONS 2 (
        PARTITION p0 VALUES LESS THAN (1990),
        PARTITION p1 VALUES LESS THAN (2000),
        PARTITION p2 VALUES LESS THAN MAXVALUE
    );
```

**Comment by evelynzhaojie** [comment]
Thanks for your question. This is the docs repository. If you have feature requirements, we appreciate that you submit a PR in https://github.com/StarRocks/starrocks/issues, the RD engineers will take care of the requirement.
