### ISSUE TITLE
[Docs Bug]: REVOKE  官方文档语法错误

### ISSUE THREAD

**Issue by dq1201** [StarRocks/docs.zh-cn#7184]
### Link to the Docs

https://docs.starrocks.io/zh/docs/2.5/sql-reference/sql-statements/account-management/REVOKE/

### Describe the Bug

![image](https://github.com/StarRocks/docs.zh-cn/assets/90668098/908be61c-6f3f-4174-80ec-ecc68cd7f077)
方框应该在库名上，文档中不止一处，请修改

**Comment by evelynzhaojie** [comment]
fixed in https://github.com/StarRocks/starrocks/pull/38092
