### ISSUE TITLE
[Docs Bug]: 文档中的md格式未生效

### ISSUE THREAD

**Issue by dq1201** [StarRocks/docs.zh-cn#7185]
### Link to the Docs

https://docs.mirrorship.cn/zh/docs/sql-reference/sql-functions/Window_function/#%E4%BD%BF%E7%94%A8-ntile-%E7%AA%97%E5%8F%A3%E5%87%BD%E6%95%B0

### Describe the Bug

![image](https://github.com/StarRocks/docs.zh-cn/assets/90668098/dd67a861-f7ba-4966-ad8c-e76a462e0f3b)

**Comment by evelynzhaojie** [comment]
thanks for your feedback, we fixed this issue in https://github.com/StarRocks/starrocks/pull/38030

**Comment by evelynzhaojie** [comment]
![image](https://github.com/StarRocks/docs.zh-cn/assets/98087056/3679abc2-3b3c-4395-88b2-d3773cccdce2)
