### ISSUE TITLE
部分函数需要补充文档

### ISSUE THREAD

**Issue by liuyehcf** [StarRocks/docs.zh-cn#724]
1. add
2. multiply
3. subtract
4. divide
5. bitmap_count
6. bitmap_union_count
7. bitmap_union_int
8. intersect_count
9. bitmap_dict
10. trim
11. upper
12. sum_distinct
13. std
14. stddev_val
15. hll_union
16. hll_raw_agg
17. ndv
18. ndv_no_finalize
19. multi_distinct_count
20. multi_distinct_sum
21. dict_merge
22. window_funnel
23. distinct_pc
24. distinct_pcsa
25. years_add
26. years_sub
27. months_add
28. months_sub
29. days_add
30. days_sub
31. adddate
32. subdate
33. date_floor
34. strftime
35. time_format
36. alignment_timestamp
37. default_value
38. replace_value

**Comment by evelynzhaojie** [comment]
all the function docs have been added, except those r&d said "no need to add doc"
