### ISSUE TITLE
[Question]: StreamLoad导入部分的示例可能是错的

### ISSUE THREAD

**Issue by trueeyu** [StarRocks/docs.zh-cn#748]
### Ask the Question

https://docs.starrocks.com/zh-cn/main/loading/StreamLoad

问题1:
```
curl --location-trusted -u root -T date -H "label:123"  -H "columns: k1, k2, v1" -T testData \ http://abc.com:8030/api/test/date/_stream_load
```

两个 -T 第一个 -T是什么意思

问题2:

实例中没有说明怎么设置分隔符，这是一个用户的常用操作

问题3:

没有说明怎么设置密码

**Comment by trueeyu** [comment]
为什么没解决，就关掉了？

**Comment by amber-create** [comment]
这个issue已经处理过了，线下文档已经更新了，等上线发布了。
