### ISSUE TITLE
Incorrect content in the "retention" function

### ISSUE THREAD

**Issue by amber-create** [StarRocks/docs.zh-cn#750]
File: [/sql-reference/sql-functions/aggregate-functions/retention.md](https://docs.starrocks.com/zh-cn/2.2/sql-reference/sql-functions/aggregate-functions/retention)
![image](https://user-images.githubusercontent.com/57167462/171607516-42cdf6eb-89f1-4028-838d-9ba4beb56422.png)

**Comment by evelynzhaojie** [comment]
fix #1202
