### ISSUE TITLE
[Docs Bug]: Wrong link

### ISSUE THREAD

**Issue by Dshadowzh** [StarRocks/docs.zh-cn#773]
### Link to the Docs

https://docs.starrocks.com/zh-cn/main/introduction/StarRocks_intro

### Describe the Bug

[更多数据库（支持 JDBC 驱动程序）](https://docs.starrocks.com/zh-cn/main/loading/Flink-connector-starrocks) , 这个链接是flink-connecotr 导入的连接，不应该放在查询的分类里面

**Comment by evelynzhaojie** [comment]
fixed
