### ISSUE TITLE
[New Content]: order by  {} [ NULLS FIRST | NULLS LAST ]  should be added

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/docs.zh-cn#776]
### Describe the Content

sr支持在order by后声明null的排序顺序在最前or最后。目前文档中还没有相关内容。

**Comment by evelynzhaojie** [comment]
@wangsimo0 有没有具体章节，是整个产品文档里所有的order by吗，可以给个截图解释一下吗

**Comment by wangsimo0** [comment]
> @wangsimo0 有没有具体章节，是整个产品文档里所有的order by吗，可以给个截图解释一下吗

https://docs.starrocks.com/zh-cn/main/sql-reference/sql-statements/data-manipulation/SELECT#order-by 我觉得在select的order by这部分加上就行

**Comment by evelynzhaojie** [comment]
fix in #3256
