### ISSUE TITLE
[Docs Bug]: Specific brand name in example

### ISSUE THREAD

**Issue by EsoragotoSpirit** [StarRocks/docs.zh-cn#814]
### Link to the Docs

https://docs.starrocks.com/zh-cn/main/sql-reference/sql-statements/data-definition/CREATE%20REPOSITORY

### Describe the Bug

There are specific brand names, such as "baidu", and "bos" in the example. Is that OK?

**Comment by evelynzhaojie** [comment]
@femiiii 用客户名称举例不太合适，可以和pm确认

**Comment by evelynzhaojie** [comment]
fix #1071 https://github.com/StarRocks/docs.zh-cn/pull/1071
