### ISSUE TITLE
[Question]: 如何同时执行多条sql

### ISSUE THREAD

**Issue by weiwei940928** [StarRocks/docs.zh-cn#828]
### Ask the Question

一下代码怎么才能执行成功 ，我尝试在配置的url后面加上&allowMultiQueries=true 但是不成功
`<delete id="batchDelete">
        delete from aa;
        delete from bb;
    </delete>`

**Comment by evelynzhaojie** [comment]
@EsoragotoSpirit 看下这个问题，是不是应该走给产研同学

**Comment by EsoragotoSpirit** [comment]
@ss892714028 Would you mind checking this issue?

**Comment by weiwei940928** [comment]
> 



> @ss892714028 Would you mind checking this issue?



> @ss892714028 Would you mind checking this issue?

就是我正常用mysql  然后使用mybatis框架 在xml里面写上述问题里的多个sql语句，然后再数据源配置那里加一个&allowMultiQueries=true是可以正常执行成功的，但是StarRocks不可以
