### ISSUE TITLE
主键模型部分增加主键模型表创建对分区的要求

### ISSUE THREAD

**Issue by dq1201** [StarRocks/docs.zh-cn#830]
### Describe the Content

https://docs.starrocks.com/zh-cn/main/table_design/Data_model#%E4%B8%BB%E9%94%AE%E6%A8%A1%E5%9E%8B

主键模型表建表时建议合理设置分区，数据更新时会以分区粒度加载对应分区主键索引到内存中，不设置分区每次导入会加载全表。请在文档的主键模型中增加这部分建议性描述。

**Comment by hellolilyliuyi** [comment]
starrocks后续都默认会用持久化索引，全加载了也不会占用多少内存
这个应该是旧版本用了内存索引下的最佳实践用法
