### ISSUE TITLE
[Docs Bug]: 

### ISSUE THREAD

**Issue by MarkovWangRR** [StarRocks/docs.zh-cn#831]
### Link to the Docs

https://docs.starrocks.com/zh-cn/main/quick_start/Import_and_query#%E6%9F%A5%E7%9C%8B-profile-%E5%B9%B6%E5%88%86%E6%9E%90%E6%9F%A5%E8%AF%A2%E7%93%B6%E9%A2%88

### Describe the Bug

开启 Profile 上报。

这个地方建议备注一下（这种set方式仅在当前session生效，因为很多用户会以为开启profile就会一直上报）

**Comment by EsoragotoSpirit** [comment]
Fixed
