### ISSUE TITLE
[New Content]: 函数示例报错

### ISSUE THREAD

**Issue by cs3163077** [StarRocks/docs.zh-cn#852]
### Describe the Content

完整的创建函数示例

### Additional Info

![image](https://user-images.githubusercontent.com/13974148/173475937-38707c21-7304-4017-a1ed-780c4ba22827.png)

**Comment by evelynzhaojie** [comment]
creat function这个命令的示例跑不通，根据文档里的语法和示例，验证这个截图里的问题
