### ISSUE TITLE
是不是可以把“使用二进制包安装”放前面，并增加集群推荐的信息

### ISSUE THREAD

**Issue by jaogoy** [StarRocks/docs.zh-cn#901]
File: [/quick_start/Deploy.md](https://docs.starrocks.com/zh-cn/main/quick_start/Deploy)

大部分用户应该是用“二进制包”来安装的，所以 docker 方式的可以放后面。

然后，应该在这个前面，放集群配置的推荐：比如
StarRocks can handle 10M-100M rows per second per CPU thread according to the complexity of your workload. And you can use it to estimate how many CPU threads do you need to meet your requirement. And StarRocks leverage column-store and compress when storing data, which can got a 4-10x compression ration. You can use it to estimate your storage volume.
见：https://starrocks.slack.com/archives/C02FAD0JSSD/p1652929332834899

**Comment by EsoragotoSpirit** [comment]
FIxed
