### ISSUE TITLE
pom.xml 直接拷贝时，考出来有很多空格和换行

### ISSUE THREAD

**Issue by jaogoy** [StarRocks/docs.zh-cn#919]
File: [/using_starrocks/JAVA_UDF.md](https://docs.starrocks.com/zh-cn/main/using_starrocks/JAVA_UDF#%E6%AD%A5%E9%AA%A4%E4%B8%80%E5%88%9B%E5%BB%BA-maven-%E9%A1%B9%E7%9B%AE)

能不能拷贝出来的就是一样格式的？

并且，这个展示本身也好多空格，感觉有些奇怪的

**Comment by evelynzhaojie** [comment]
已添加拷贝按钮，现在拷贝出来格式正常。
![image](https://user-images.githubusercontent.com/98087056/215755018-125fcf00-926d-460b-afc5-0dc756dddfe9.png)
