### ISSUE TITLE
这个window function 的 over()语法的“可选”描述有些问题

### ISSUE THREAD

**Issue by jaogoy** [StarRocks/docs.zh-cn#941]
File: [/using_starrocks/Window_function.md](https://docs.starrocks.com/zh-cn/main/using_starrocks/Window_function)

over()中的3个部分都是可选的，并且相互独立。
OVER([partition_by_clause] [order_by_clause] [window_clause])

不过，可能 window_clause 必须在有 order_by_clause 下。

这个 check 清楚，再修改下。

**Comment by EsoragotoSpirit** [comment]
> File: [/using_starrocks/Window_function.md](https://docs.starrocks.com/zh-cn/main/using_starrocks/Window_function)
> 
> over()中的3个部分都是可选的，并且相互独立。 OVER([partition_by_clause] [order_by_clause] [window_clause])
> 
> 不过，可能 window_clause 必须在有 order_by_clause 下。
> 
> 这个 check 清楚，再修改下。

已确认，窗口从句必须位于 Order By 从句下。

问题将在相应走读PR中修复。
