### ISSUE TITLE
[New Content]: 补充SHOW CREATE TABLE命令

### ISSUE THREAD

**Issue by hellolilyliuyi** [StarRocks/docs.zh-cn#982]
### Describe the Content

补充SHOW CREATE TABLE命令

**Comment by femiiii** [comment]
指的是这篇文档吗？https://docs.starrocks.com/zh-cn/main/sql-reference/sql-statements/Administration/SHOW%20TABLE%20STATUS#%E7%A4%BA%E4%BE%8B

**Comment by howrocks** [comment]
+ SHOW CREATE VIEW
